### ISSUE TITLE
Typesafe Config files should be merged in reverse classpath order

### ISSUE THREAD

**Issue by andyscott** [sbt/sbt-assembly#111]
Consider the following scenario. An application consists of myapp.jar above foolib.jar in the classpath.
- myapp.jar contains reference.conf with `test = myapp`.
- foolib.jar contains reference.conf with `test = foolib`.

If I run this application using the default Typesafe config setup, `test` will be `myapp`. The reference.conf files are merged with the files higher in the classpath taking precedence over those lower in the classpath. ([source](https://github.com/typesafehub/config/blob/v1.2.0/config/src/main/java/com/typesafe/config/impl/Parseable.java#L579))

However, if I generate an assembly, reference.conf will be concatenated in the same order, yielding:

```
test = myapp
test = foolib
```

When the assembled application is ran, `test` will be `foolib` because statements towards the end of individual files take precedence.

The behavior of the two cases is inconsistent and confusing when encountered. By default, might be it be a good idea to merge config files in reverse classpath order? It'd be very easy to add a `reverseConcat` merge strategy and make it the default for config files.

```
val reverseConcat: MergeStrategy = new MergeStrategy {
  val name = "reverseConcat"
  def apply(tempDir: File, path: String, files: Seq[File]): Either[String, Seq[(File, String)]] =
    MergeStrategy.concat(tempDir, path, files.reverse)
}

//...
val defaultMergeStrategy: String => MergeStrategy = { 
  case x if Assembly.isConfigFile(x) =>
    MergeStrategy.reverseConcat
  //...
}
```

Caveat of the above code: `isConfig` currently handles non typesafe config files... and I'm not sure if they are affected the same way.

**Comment by stephenmcd** [comment]
Just got bitten by this as well - reference.conf from within akka gets appended to my own reference.conf, overriding it which as mentioned is the opposite of the usual behaviour when run with sbt.

`reverseConcat` approach above fixes it.

**Comment by Locke** [comment]
This affected me too, but I'd vote against the reverseConcat approach. I suggest to resolve this with a nested config:

reference.conf:
```
myapp {
  test = myapp
}
```

example.scala:
``` scala
val baseConfig = ConfigFactory.load()
val config = baseConfig.getConfig("myapp").withFallback(baseConfig)
val test = config.getValue("test") // will be myapp
```

**Comment by dvirf** [comment]
@Locke relying on the method of loading the config with fallback is only good if all the components of your app do this as well.
For example, if you have a third-party sbt-plugin that uses `ConfigFactory.load()`, it will not get **your** overrides.

My merge settings are similar to @andyscott's and @stephenmcd's :
```
val reverseConcat: MergeStrategy = new MergeStrategy {
  val name = "reverseConcat"
  def apply(tempDir: File, path: String, files: Seq[File]): Either[String, Seq[(File, String)]] =
    MergeStrategy.concat(tempDir, path, files.reverse)
}

assemblyMergeStrategy in assembly := {
  case "BUILD" => MergeStrategy.discard
  case fileName if fileName.toLowerCase == "reference.conf" => reverseConcat
  case other => MergeStrategy.defaultMergeStrategy(other)
}
```

**Comment by tuannh99** [comment]
@dvirf Thank you.
I'm trying to rewrite it for build.sbt file. Could you please suggest me how to have reverseConcat strategy?

**Comment by dvirf** [comment]
Hi @tuannh99, glad to help :)
I'm not sure I follow your question.

If you want to edit the code for sbt-assembly, then it should be added under `MergeStrategy.scala`, [here](https://github.com/sbt/sbt-assembly/blob/master/src/main/scala/sbtassembly/MergeStrategy.scala#L24), similar to the strategies `first`, `last`, etc.

However, if you want to add a custom strategy to your own project, and keep using the existing version of sbt-assembly, then you should add the [code on my last comment](https://github.com/sbt/sbt-assembly/issues/111#issuecomment-228601062) to your `build.sbt` file.

**Comment by tuannh99** [comment]
@dvirf Thank you for your help.

I think this block of code is supposed for build.scala file, and NOT syntax correctly for build.sbt, am I right?
I tried it for my project's build.sbt file, it failed.

**Comment by dvirf** [comment]
@tuannh99 it is correct for build.sbt.
add `import sbtassembly.MergeStrategy` to your build.sbt file.

**Comment by tuannh99** [comment]
@dvirf It turned out my problem should be solved by disabling assemblyPlugin on some submodules.
Thank you really much for your help.

**Comment by LeifW** [comment]
This fix works for us - thanks!

**Comment by LeifW** [comment]
Curious why there's `MergeStrategy.first` and `MergeStrategy.last` if the order isn't supposed to be relied on...
