### ISSUE TITLE
META-INF manifest is discarded on ducplication

### ISSUE THREAD

**Issue by allenanie** [sbt/sbt-assembly#119]
My original post on Stackoverflow is here: http://stackoverflow.com/questions/24610719/meta-inf-manifest-is-discarded-on-ducplication

I was suggested to open a new issue. Here's the problem that I run into:

```
[info] Merging files...
[warn] Merging 'META-INF\INDEX.LIST' with strategy 'discard'
[warn] Merging 'META-INF\MANIFEST.MF' with strategy 'discard'
```

The problem is that I have a duplicated MANIFEST file in a third-party jar, so sbt-assembly is not creating my own MANIFEST file.

**Comment by prayagupd** [comment]
Given two two modules, `A` and `B`, putting `mainClass` on root `build.sbt` works, but not on `A/build.sbt`

```scala
organization := "com.prayagupd"

name := "upd-backend"

version := "1.0"

scalaVersion := "2.12.6"

mainClass in assembly := Some("com.prayagupd.admin.App")

lazy val root = Project(id = "root",
  base = file(".")) aggregate(client, service) dependsOn(client, service)

lazy val client = Project(id = "client",
  base = file("admin-client"))

lazy val service = Project(id = "service",
  base = file("admin-service")) dependsOn client
```
