### ISSUE TITLE
Runtime-only library is not included in the assembly jar

### ISSUE THREAD

**Issue by mengxr** [sbt/sbt-assembly#120]
In Spark, we have jets3t defined in the runtime scope but not in compile. However, this jar is not included in the assembly jar if built with sbt-assembly. We confirmed that this jar is in runtime:full-classpath and Maven's assembly build works fine. Does sbt-assembly include runtime-only jars by default?

PR: https://github.com/apache/spark/pull/1402

**Comment by yinrong** [comment]
latest sbt still not working. and the above methods are all deprecated
