### ISSUE TITLE
Merge Strategy Type Mismatch

### ISSUE THREAD

**Issue by chipsenkbeil** [sbt/sbt-assembly#121]
I tried following the example in the README regarding adding rules to the existing merge strategy, but I seem to be getting a type mismatch. `expected: Def.Initialize[(String) => Plugin.MergeStrategy], actual: Def.Initialize[Any]`

I'm using _sbt 0.13.5_ and _Scala 2.10.4_.

The following is inside my _assembly.sbt_ file:

```
import AssemblyKeys._ // put this at the top of the file

assemblySettings

mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) => {
      case PathList("META-INF", "ECLIPSEF.RSA") => MergeStrategy.discard
      case x => old(x)
    }
  }
```

I'm using version _0.11.2_ of the assembly plugin. The following is my _project/plugins.sbt_ file:

```
logLevel := Level.Warn

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.11.2")
```

**Comment by asheshambasta** [comment]
I'm about to give up on getting this to work:

```
-> % sbt clean
[info] Loading global plugins from /Users/asheshambasta/.sbt/0.13/plugins
/Users/asheshambasta/code/centralapp/finagle/project/assembly.sbt:1: error: not found: object AssemblyKeys
import AssemblyKeys._
       ^
sbt.compiler.EvalException: Type error in expression
```

Anyone else having this problem? I'm also trying this out with `0.11.2`.
