### ISSUE TITLE
Cannot upgrade to 0.12.0 - Documentation / bug duplicate plugin files

### ISSUE THREAD

**Issue by samthebest** [sbt/sbt-assembly#139]
(headers added by @eed3si9n)
## steps

I've changed by plugins.sbt in project-root/project/ from

```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.11.2")
```

to

```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.12.0")
```

My build is has path project-root/build.sbt
## problem

When I try to then run `sbt clean` I get:

```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.eed3si9n:sbt-assembly:0.11.2 -> 0.12.0
[warn] Run 'evicted' to see detailed eviction warnings
project-root/build.sbt:1: error: not found: object AssemblyKeys
import AssemblyKeys._
       ^
sbt.compiler.EvalException: Type error in expression
    at sbt.compiler.Eval.checkError(Eval.scala:384)
    at sbt.compiler.Eval.compileAndLoad(Eval.scala:183)
    at sbt.compiler.Eval.evalCommon(Eval.scala:152)
    at sbt.compiler.Eval.evalDefinitions(Eval.scala:122)
    at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:254)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:109)
...
```
## notes

FYI, when I was on 0.11.2 I actually got my build file to work by using a different import statement:

```
import sbtassembly.Plugin.AssemblyKeys._
```

But now when I try that I get:

```
error: not found: object sbtassembly
import sbtassembly.Plugin.AssemblyKeys._
       ^
sbt.compiler.EvalException: Type error in expression
    at sbt.compiler.Eval.checkError(Eval.scala:384)
    at sbt.compiler.Eval.compileAndLoad(Eval.scala:183)
    at sbt.compiler.Eval.evalCommon(Eval.scala:152)
    at sbt.compiler.Eval.evalDefinitions(Eval.scala:122)
...
```
## steps2

I've tried reading this: https://github.com/sbt/sbt-assembly/blob/master/Migration.md so removing the import statement and `assemblySettings` altogether, but now then I get
## problem2

```
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: assembly
[error] assembly
[error]
```
## notes2

My sbt version is 0.13.6:

```
> sbt sbtVersion
...
[info] 0.13.6
```

I tried renaming `build.sbt` to `assembly.sbt`, it changed nothing.
## steps3

Finally I noticed in the main documentation that it says the plugin file should go in here "project/assembly.sbt", my plugins file was called "project/plugins.sbt", so I thought let's try renaming that.  Before I renamed it I realised it already existed with contents exactly `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.11.2")`.  This explained the weird evicting warning.  So I deleted the "project/assembly.sbt" leaving just my "project/plugins.sbt" and I think it works now.
## expectations

Please could you:
1. When multiple files exist rather than give eviction warning, give something along the lines of "this file says this version, and this file says this version" or something.  Basically the eviction warning is somewhat cryptic.  Even if the versions are consistent it should give some kind of helpful warning that you have two plugins files.
2. Perhaps when migrations completely break existing build files in rather strange ways, it would be good to have a special pre-parser stage that does a quick check that users don't still have "import AssemblyKeys._" at the top of their file and give them a helpful message rather than `error: not found: object AssemblyKeys` you could say `you don't need the import any more`.
3. Clarify documentation on the names of these files should be, if the name doesn't actually matter then say this explicitly. E.g. put your plugins here: "project/some-file-name-up-to-you.sbt"

Many thanks,

**Comment by eed3si9n** [comment]
Thanks for the detailed report on migration experience. It seems like you were eventually able to upgrade to the latest, but found the documentation and error messages in sbt to be confusing.

> 1. When multiple files exist rather than give eviction warning...

Without the eviction warning it would have just displayed

```
project-root/build.sbt:1: error: not found: object AssemblyKeys
import AssemblyKeys._
       ^
``` 

and eviction warning actually gives you the hint that there is duplicate plugins.
However, eviction warning (or its replacement that you are proposing) is an sbt feature, not sbt-assembly's so maybe we should discuss that on sbt-dev.

> 2. Perhaps when migrations completely break existing build files in rather strange ways...

Again, this would need to be embedded deep inside sbt's parser, which uses Scala compiler to handle this, but I would give this more thoughts on how we can improve this experience around migration.

> 3. Clarify documentation on the names of these files should be...

This is something I can work on in sbt-assembly.

**Comment by eed3si9n** [comment]
I am closing this since ppl have likely moved on to the current plugin.
