### ISSUE TITLE
sbt-assembly 0.12.0: excluding tests during assembly does not work

### ISSUE THREAD

**Issue by arun936** [sbt/sbt-assembly#140]
I am following the instructions in:

https://github.com/sbt/sbt-assembly#assembly-task

I have added the statement:

```scala
test in assembly := {}
```

to my build.sbt. However, tests are run during assembly, e.g., "sbt assembly".

This is for sbt 0.13.7.

**Comment by eed3si9n** [comment]
I can't reproduce your problem:

```scala
lazy val commonSettings = Seq(
  scalaVersion := "2.10.4"
)

lazy val app = (project in file("app")).
  settings(commonSettings: _*).
  settings(
    libraryDependencies += "org.specs2" %% "specs2-core" % "2.4.15" % Test,
    test in assembly := {}
  )
```

**Comment by arun936** [comment]
Your note clarified things for me. I didn't realize that the line
  test in assembly := {}
had to appear in each project settings. I had it at the global level.

Putting it in the project settings works as advertised.

Thanks!
arun
