### ISSUE TITLE
Error assembling new Play 2.3.7 project

### ISSUE THREAD

**Issue by ms-tg** [sbt/sbt-assembly#143]
Hi Eugene, great to meet you at NEScala! Thanks for any help with this.

We created a new Play 2.3.7 project, and added sbt-assembly as described in the Play docs:
* https://www.playframework.com/documentation/2.3.x/ProductionDist

As discussed, I'll cross-post this issue to Play, and submit a Typesafe support request for it.
```
[orguniversesui] $ assembly
...
[trace] Stack trace suppressed: run last orguniversesui/*:assembly for the full output.
[error] (orguniversesui/*:assembly) deduplicate: different file contents found in the following:
[error] /Users/msiegel/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.3.7.jar:play/core/server/ServerWithStop.class
[error] /Users/msiegel/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.3.7.jar:play/core/server/ServerWithStop.class
...
```

**Comment by benmccann** [comment]
I don't know enough about Scala, but perhaps the trait ServerWithStop and the class ServerWithStop are colliding

    ./framework/src/build-link/src/main/java/play/core/server/ServerWithStop.java
    ./framework/src/play/src/main/scala/play/core/server/NettyServer.scala (contains trait ServerWithStop)

I'd also recommend checking out [sbt-native-packager](https://github.com/sbt/sbt-native-packager) for packaging as a way to get around this problem

**Comment by eed3si9n** [comment]
Looks like there's movements on playframework/playframework#3873 so I'm closing this.
