### ISSUE TITLE
Which repository sbt-assembly 0.13.0 is stored in?

### ISSUE THREAD

**Issue by alexd84** [sbt/sbt-assembly#148]
When I add sbt plugin addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.13.0"), i get following error:
com.eed3si9n#sbt-assembly;0.13.0: not found

Scala version 2.10.1

Is there specific repository with this plugin?

**Comment by alexd84** [comment]
I

**Comment by eed3si9n** [comment]
sbt plugin repo as usual:
- https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.13.0/
