### ISSUE TITLE
Any way to avoid rebuilding dependencies and scala jars if build files unchanged?

### ISSUE THREAD

**Issue by axos88** [sbt/sbt-assembly#149]
Hello,

Please add a method that would prevent rebuilding the dependency and the scala jars in case they have not changed.

During development I deploy three jars to speed up the transfer:
  - assemblyPackageDependency jar (huge)
  - assemblyPackageScala jar (medium-size)
  - packageBin jar (small)

If this was possible, it would speed my process a lot.

**Comment by eed3si9n** [comment]
I think the current implementation already caches output under `target`. If it's not working for you, please submit small test case to demonstrate the bug.

**Comment by axos88** [comment]
Yes it is.
