### ISSUE TITLE
not found: value defaultShellScript

### ISSUE THREAD

**Issue by JingyuZHANG** [sbt/sbt-assembly#153]
sbt.version=0.13, scalaVersion =  "2.11.6" and sbt-assembly "0.13.0"

Error is 
/project/BuildSettings.scala:51: not found: value defaultShellScript 
[error]     assemblyOption in assembly := (assemblyOption in assembly).value.copy(prependShellScript = Some(defaultShellScript)),                                                                                                 
[error] one error found
[error] (compile:compileIncremental) Compilation failed
--BuildSettings.scala---

// sbt-assembly settings for building a fat jar
 import sbtassembly.AssemblyPlugin.autoImport._
lazy val sbtAssemblySettings = Seq(
    // Executable jarfile
    assemblyOption in assembly := (assemblyOption in assembly).value.copy(prependShellScript = Some(defaultShellScript)),
   // Name it as an executable
    jarName in assembly := { s"${name.value}-${version.value}" }
  )
  lazy val buildSettings = basicSettings ++ scalifySettings ++ sbtAssemblySettings
}

**Comment by fehmicansaglam** [comment]
Same here. sbt: 0.13.8, scala: 2.11.6

```scala
assemblyOption in assembly := (assemblyOption in assembly).value.copy(prependShellScript = Some(defaultShellScript))

assemblyJarName in assembly := s"${name.value}-${version.value}"
```

gives the error below: 

```
build.sbt:25: error: not found: value defaultShellScript
assemblyOption in assembly := (assemblyOption in assembly).value.copy(prependShellScript = Some(defaultShellScript))
```

**Comment by fehmicansaglam** [comment]
After importing `import sbtassembly.AssemblyPlugin.defaultShellScript` problem is resolved.
