### ISSUE TITLE
Support for shading

### ISSUE THREAD

**Issue by ogirardot** [sbt/sbt-assembly#156]
Hi, 
First of all, thank you ! It's a really great plugin ! 
Would it be possible to add shading feature like the maven-shade-plugin ? or is there any other plugin that can be used with sbt-assembly to do so ?

Regards, 

Olivier.

**Comment by whjiang** [comment]
This is a feature we are seeking for. Is there any way to do it in sbt?

**Comment by mattweyant** [comment]
+1

**Comment by kzarzycki** [comment]
+1 !! 
That's a enormously needed feature by a lot of people I talk to. Currently we have an ugly hack of having gradle build on top of sbt build, that does just the shading. We would love to be purely sbt and sbt-assembly can help with that.

**Comment by eed3si9n** [comment]
- http://stackoverflow.com/q/24596914/3827
- http://stackoverflow.com/q/28846389/3827

**Comment by eed3si9n** [comment]
I don't think I have enough free time to get myself into porting the shading feature.
I'd be happy to assist in either making it a standalone plugin or an additional feature of sbt-assembly, if people want to collaborate to implement it.

**Comment by eed3si9n** [comment]
sbt-assembly 0.14.0 is out with shading support thanks to @wxiang7 - http://notes.implicit.ly/post/128778161214/sbt-assembly-0140

**Comment by ogirardot** [comment]
that's great news !!!
Thanks a lot @wxiang7

2015-09-10 16:46 GMT+02:00 eugene yokota <notifications@github.com>:
