### ISSUE TITLE
Error: invalid or corrupt jarfile

### ISSUE THREAD

**Issue by sangszhou** [sbt/sbt-assembly#161]
I encountered this problem when executing a fat jar built by sbt-assembly. From https://github.com/sbt/sbt/issues/850 , I got a work around solution by using

java -cp app.jar app.Main

After that, I digged a little bit and found that unzipping the fat jar and zip it again,

java -jar app.jar won’t report error

So, I guess it probably has something to do with the zip related code in sbt assembly and jdk1.7 somehow cannot recognize jar file.

**Comment by jramos** [comment]
@sangszhou, I'm stuck on the same issue. How did you reassemble the fat JAR?

**Comment by sangszhou** [comment]
@jramos 
I didn't reassemble the fat jar, just changed the way how to execute jar.

`java -cp app.jar app.Main` works for me.
