### ISSUE TITLE
only assemble the root project

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-assembly#168]
I have a multi-project build file (its ensime) and I tried setting `assembleArtifact in assembly := false` for everything except the root project, but an `sbt ensime/assembly` (`ensime` is the name of our root project) shows that all the submodule fat jars are still being created.

**Comment by eed3si9n** [comment]
Sorry that a bug #147, which I forgot to fix. Try

```
aggregate in assembly := false
```

**Comment by fommil** [comment]
great! that worked :smile: are you going to scalaworld?

**Comment by fommil** [comment]
i guess if you haven't fixed it this ticket can be left open... but I'm happy with the soln.

**Comment by eed3si9n** [comment]
I am, and I have a few unconference talk ideas too - https://scala.world/unconference

**Comment by fommil** [comment]
I was going to give one about ENSIME but my wife is going to join me for the weekend, so while you're all doing the unconference I'll be getting a massage in the spa :stuck_out_tongue: (or, actually, am I the fool here??)

**Comment by eed3si9n** [comment]
Sounds like a good idea esp if you're going on hiking.

**Comment by stevegreen22** [comment]
Hi,

Could you confirm on the resolution to this?  Following the other post suggests that aggregate in assembly didn't work and instead the suggestion for disabling the plugin in that module was the workaround - thanks.
