### ISSUE TITLE
assemble sources

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-assembly#169]
FYI, I asked the FSF about LGPL code included in fat jars of apps that are Apache v2 and they said it is perfectly fine! That's one major myth about the LGPL dispelled.

They said that so long as end users can repackage the jar file with alternative implementations of the LGPL classfiles and that the sources are available according to Section 6 of the GPL (note that it is enough to point at the github repo of the LGPL components). However, I think it would be nice to also provide full assembled source jars and it would be good if this plugin created them.

Also producing a LICENSE summary would be neat.

**Comment by jvican** [comment]
Yes, this would be nice.
