### ISSUE TITLE
dependencies in ivy when publishing assembled jar

### ISSUE THREAD

**Issue by ShengC** [sbt/sbt-assembly#176]
Shouldn't there be no dependencies at all in ivy file when _only_ the assembled jar needs to be published. I know this is an unusual use case, but it would be good if the plugin can provide such flexibility.

I am currently making use of this terrible hack

    deliver := {
      val f = deliver.value
      IO.write(f, io.Source.fromFile(f).getLines.toList.filterNot(_.trim.startsWith("<dependency")).mkString("\n"))
      f
    }

**Comment by eed3si9n** [comment]
In general I don't want to encourage publishing fat jars as artifacts. If you must, I recommend you create another subproject to do it.
