### ISSUE TITLE
Overriding the special handling of "provided" dependencies 

### ISSUE THREAD

**Issue by matanster** [sbt/sbt-assembly#178]
It would be nice allowing to override the [special handling of `provided`](https://github.com/sbt/sbt-assembly#-provided-configuration), to _include_ the `provided` dependencies in the fatjar. The scenario this would help with, is a compiler plugin that has dependencies. This scenario is described in https://github.com/sbt/sbt/issues/2255, its uniqueness stemming from the special case of a compiler plugin. Frankly I had been suggested on the gitter channel to try something like:

```
mappings in (packageBin, assembly) ++= (mappings in (Compile, packageBin) in <Plugins' dependency>).value
```

..but didn't get very far with that suggestion as I did not really fathom how or whether mappings can be used to add the results of dependencies' compilation to the artifact - I saw little documentation about manipulating assembly mappings, and worked around the issue for now. (My workaround described in the referenced sbt ticket).

**Comment by SethTisue** [comment]
I hit this same situation (compiler plugin with dependencies) over in a private repo.

what I ended up doing was declaring the dependencies as `provided` but then doing this to keep them from being filtered out of the JAR:

    fullClasspath in assembly := (fullClasspath in Compile).value

I record it here as a possibly useful workaround.

**Comment by SethTisue** [comment]
in the same private repo, @eed3si9n commented:

It's fairly common for library authors having to hack around the discrepancies between `pom.xml`/`ivy.xml` vs "what I need for fat JAR." There are two methods to work around this.

### front business

First approach is to make a subproject for fat JAR purpose only where you depend on the stuff, and make a second _cosmetic_ subproject that you use only for publishing purpose:

```scala
lazy val fatJar = project
  .enablePlugins(AssemblyPlugin)
  .settings(depend on the good stuff)

lazy val cosmetic = project
  .settings(
    // I am sober. no dependencies.
    packageBin in Compile := (assembly in (fatJar, Compile)).value  
  )
```

### xml hacking

Second, a more direct approach is to let sbt generate `pom.xml` or `ivy.xml` first and directly mess with the XML. This is done sometimes by ppl who shades other libraries. See https://github.com/playframework/play-ws/pull/72/commits/5a12c092e6f2a585eb70e3e554c46cf79aef1f16

```scala
lazy val shadedX = project
  .enablePlugins(AssemblyPlugin)
  .settings(
    depend on the good stuff,
     // Remove dependencies from the POM because we have a FAT jar here.
     makePomConfiguration := makePomConfiguration.value.copy(process = dependenciesFilter),
     ivyXML := <dependencies></dependencies>,
   )

import xml.{NodeSeq, Node => XNode, Elem}
import xml.transform.{RuleTransformer, RewriteRule}

def dependenciesFilter(n: XNode) = new RuleTransformer(new RewriteRule {
  override def transform(n: XNode): NodeSeq = n match {
    case e: Elem if e.label == "dependencies" => NodeSeq.Empty
    case other => other
  }
}).transform(n).head
```

**Comment by eed3si9n** [comment]
I guess @SethTisue's solution can be used to close this issue.

I'll move my comments to the readme.
