### ISSUE TITLE
sbt-assembly case insensitive?

### ISSUE THREAD

**Issue by gshaked** [sbt/sbt-assembly#180]
I'm trying to use sbt-assembly with an unmanaged jar which has classes which are case sensitive. i.e. it may have both ABC.class and Abc.class. 
the assembly leaves only one of the classes, is there some configuration to make sure both will be packaged? 
I'm using sbt-assembly 0.14.0

**Comment by eed3si9n** [comment]
Both Windows and Mac by default uses case insensitive filesystem I think. sbt-assembly unzips all the files from jars, so that could cause your issue?

**Comment by mjaghouri** [comment]
Any solution already to that?
I am having the same problem.
