### ISSUE TITLE
remove scalactic dependency

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-assembly#185]
it makes it harder to copy&paste the plugin code to be used in internal projects. jarjar is also a pain, but I guess we can't get around that one.

(not everybody has access to maven central or bintray, or indeed any kind of standard resolver)

**Comment by eed3si9n** [comment]
If someone wants to copy-paste or reimplement error accumulation that can retain the feature implemented in #144, I'll consider it.

**Comment by fommil** [comment]
I'm increasingly starting to believe that good practice for an sbt-plugins is one that fits in one file (so it can be installed by copy/paste), with no dependencies (unless absolutely necessary, and even then customisable `libraryDependencies` / `unmanagedJars`).

I might refactor my own plugins to meet this criteria. Being inside a corporate firewall without maven-central (or regularly packaged artefacts) really makes one rethink these things.

My priority for this dropped, as I got a workaround that really shouldn't work, but it does.
