### ISSUE TITLE
Minimizing a JAR

### ISSUE THREAD

**Issue by simplyianm** [sbt/sbt-assembly#186]
The Maven shade plugin allows minimizing a JAR; that is, removing classes that are not used by the project. Is there a way you can implement that for this project?

**Comment by eed3si9n** [comment]
Not 100% sure but I'm guessing that's what `ShadeRule.keep("x.**").inAll` does.
See also

- https://code.google.com/p/jarjar/wiki/CommandLineDocs
- https://github.com/sbt/sbt-proguard

**Comment by LannyRipple** [comment]
For anyone finding this ticket this might help.

Create a fat jar and your code jar.  Use "java -jar jarjar.jar find class code.jar fat.jar" to list dependencies.  You can use this output to create "keep" rules and process the fat jar (again with jarjar) to get your minimized jar.

**Comment by eed3si9n** [comment]
sbt-assembly has jarjar instegration for `keep`. The `find class` thing looks interesting too.

**Comment by johnduffell** [comment]
LannyRipple is right, you have to create a fat jar and then run keep on that afterwards as sbt-assembly produces a broken fat jar if you try to use keep.  in most cases it will omit all classes from the dependency jars.  See my comment on https://github.com/sbt/sbt-assembly/issues/265#issuecomment-410464756
