### ISSUE TITLE
sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.0: not found

### ISSUE THREAD

**Issue by ahkimkoo** [sbt/sbt-assembly#187]
sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.0: not found

sbt launcher version 0.13.8

**Comment by jarandaf** [comment]
@ahkimkoo which `scalaVersion` are you using? I had `scalaVersion := "2.11.6"` in `~/.sbt/0.13/global.sbt` and had to remove it. Check [this](http://stackoverflow.com/questions/32720365/sbt-assembly-unresolved-dependency-scala) out.

**Comment by eed3si9n** [comment]
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.0/ seems to be there.
