### ISSUE TITLE
merge issue for multi projects

### ISSUE THREAD

**Issue by liu-hongwei** [sbt/sbt-assembly#191]
hello,

i am using sbt-assembly plug in to generate flat jars for my projects. the projects folder layout as below:

+--Platform
     |--project
     |--build.sbt                                  
     |-- SDK
     |       |-project
     |       |-src
     |       |-build.sbt
     |-- Apps
     |      |-project
     |      |-build.sbt
     |      |-App001
     |          |-project
     |          |-src
     |          |-build.sbt
     |      |-App002
            ....
 
so this is a multi projects, /Platform is the root.
the /Platform/build.sbt as below:
//------------------------------------------------------
lazy val commonSettings = Seq(
   organization := "com.abc",
   scalaVersion := "2.11.6"
)
lazy val sdksproj = (project in file("./SDK/")).
    settings(commonSettings: _*).
	settings(
		version := "1.0",
		name := "sdk-scala",
		publishArtifact  := true
	)

lazy val appsproj = (project in file("./Apps")).
    settings(commonSettings: _*).dependsOn(sdksproj)

publishArtifact  := false

publishTo := Some(Resolver.file("file",  new File(Path.userHome.absolutePath+"/.m2/repository")))

assembly := {
  (assembly in (sdksproj, assembly)).value
  (assembly in (appsproj, assembly)).value
}

fork := true

javaOptions in assembly += "-Xmx4G -XX:MaxMetaspaceSize=1G -XX:MaxPermSize=1G -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

lazy val rootproj = (project in file(".")).
					aggregate(sdksproj, appsproj).
					settings(
						aggregate in update := false,
					    aggregate in assembly := true,
					    name := "com.abc.platform"
					)

					
assemblyMergeStrategy in assembly := {
	case PathList("META-INF", xs @ _*) => MergeStrategy.discard
	case PathList(ps @ _*) if ps.last endsWith ".class" => MergeStrategy.last
	case x => MergeStrategy.first
}
//------------------------------------------------------

for the /Platform/Apps/build.sbt, it is only used to declare the projects under Apps folder:
//------------------------------------------------------
lazy val commonSettings = Seq(
   organization := "com.abc",
   scalaVersion := "2.11.6"
)

lazy val app001 = (project in file("./App001")).
    settings(commonSettings: _*)

lazy val app002 = (project in file("./App002")).
    settings(commonSettings: _*)

//------------------------------------------------------

the build.sbt in App001, App002, ... are regular sbt file to set for the individuals.

all seems good if i build them separately from their folder by running "sbt assembly" command. 
however,  if i run from the root /Platform folder with command "sbt assembly", i get tons of errors like this:

[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/InfBlocks.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/InfCodes.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/InfCodes.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/InfTree.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/InfTree.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/Inflate$1.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/Inflate$1.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/Inflate.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/Inflate.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/JZlib$WrapperType.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/JZlib$WrapperType.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/JZlib.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/JZlib.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/StaticTree.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/StaticTree.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/Tree.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/Tree.class
[error] deduplicate: different file contents found in the following:
[error] C:\Users\eybcegc\.ivy2\cache\org.jboss.netty\netty\bundles\netty-3.2.2.Final.jar:org/jboss/netty/util/internal/jzlib/ZStream.class
[error] C:\Users\eybcegc\.ivy2\cache\io.netty\netty\bundles\netty-3.8.0.Final.jar:org/jboss/netty/util/internal/jzlib/ZStream.class
[error] Total time: 118 s, completed Dec 8, 2015 9:18:25 AM

please note in the /Platform/build.sbt, i have already set the merge strategy like this:

assemblyMergeStrategy in assembly := {
	case PathList("META-INF", xs @ _*) => MergeStrategy.discard
	case PathList(ps @ _*) if ps.last endsWith ".class" => MergeStrategy.last
	case x => MergeStrategy.first
}

so  where am i wrong?  

i have no idea now how to resolve this.

any help is appreciated. 

thanks in advance.

Hongwei

**Comment by eed3si9n** [comment]
The sbt-assembly issue tracker is not a support system. Please see https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
