### ISSUE TITLE
Fail to shade aws sdk 

### ISSUE THREAD

**Issue by ale64bit** [sbt/sbt-assembly#192]
I'm have a project with the following dependencies (among many others):
```
val aws = "1.10.33"
"com.amazonaws" % "aws-java-sdk-emr" % aws,
"org.apache.hadoop" % "hadoop-hdfs" % "2.7.1",
"org.apache.hadoop" % "hadoop-aws" % "2.7.1",
"org.apache.hadoop" % "hadoop-common" % "2.7.1"
```
Since `hadoop-aws` depends on `"com.amazonaws" % "aws-java-sdk" % "1.7.4"`, I'm trying to shade one of those (either "1.10.33" or "1.7.4") so they can coexist in my project. I added the following rule (and many variations as well):
```
ShadeRule.rename("com.amazonaws.**" -> "shadedstuff.awscore.@1").inLibrary("com.amazonaws" % "aws-java-sdk" % "1.7.4").inAll
```
But unfortunately, I only manage to get both artifacts shaded or none of them at all (both cases lead to annoying dedup errors). How to shade that specific dependency?

**Comment by eed3si9n** [comment]
The sbt-assembly issue tracker is not a support system. Please see https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report

**Comment by voukka** [comment]
Run into the same problem. Why was the issue closed? It looks like a bug, isn't it?

**Comment by ale64bit** [comment]
@eed3si9n Maybe the wording wasn't accurate and looks for support request. Consider my project [build.sbt](https://gist.github.com/ale64bit/b4a2572adbd6982fe2ee) without shading. In this case I get the following (trivial?) dedup errors:
```
[error] deduplicate: different file contents found in the following:
[error] /Users/username/.ivy2/cache/com.amazonaws/aws-java-sdk-core/jars/aws-java-sdk-core-1.10.33.jar:com/amazonaws/util/json/Jackson.class
[error] /Users/username/.ivy2/cache/com.amazonaws/aws-java-sdk/jars/aws-java-sdk-1.7.4.jar:com/amazonaws/util/json/Jackson.class
```
If I add a shading rule for shading the offending library (which is used by Hadoop internally) as in this [project file](https://gist.github.com/ale64bit/0768cadf3f1a4a568eca), then I get the following dedup errors:
```
[error] deduplicate: different file contents found in the following:
[error] /Users/username/.ivy2/cache/com.amazonaws/aws-java-sdk-core/jars/aws-java-sdk-core-1.10.33.jar:shadedstuff/awscore/util/json/Jackson.class
[error] /Users/username/.ivy2/cache/com.amazonaws/aws-java-sdk/jars/aws-java-sdk-1.7.4.jar:shadedstuff/awscore/util/json/Jackson.class
```
As you can see, it looks like both libraries are being shaded (while I only wanted to shade the old 1.7.4 version). Is this a bug or a misunderstanding of the capabilities/usage of the plugin? Thanks.

**Comment by eed3si9n** [comment]
@voukka:

> Run into the same problem. Why was the issue closed? It looks like a bug, isn't it?

I'm not too sure.

@ale64bit 

> I also asked in SO about this issue.

Thanks. Answered the question. Hopefully that clarifies what might be going on.

**Comment by ale64bit** [comment]
@eed3si9n @voukka Not an issue. See [here](http://stackoverflow.com/questions/34205953/how-to-deduplicate-beanutils-dependencies-with-sbt-assembly) for details.

**Comment by eed3si9n** [comment]
Glad we were able to resolve this.
