### ISSUE TITLE
"Type error in expression"  when skip test 

### ISSUE THREAD

**Issue by abel-von** [sbt/sbt-assembly#193]
I want to skip test when assembling. so  i run with  sbt "set test in assembly := {}" assembly. 
however, an error happened and the result is showing like this 

<set>:1: error: not found: value assembly
test in assembly := {}
        ^
[error] Type error in expression

my sbt version is 0.13.8   and  my sbt-assembly version is "com.eed3si9n" % "sbt-assembly" % "0.11.2".

Now i can only skip test with  "set every test := {}" and this works.

So this really confusing me because when in the interactive mode, the auto-complete can pop up the "assembly" option when i type "set test in " and TAB.

**Comment by eed3si9n** [comment]
The sbt-assembly issue tracker is not a support system. Please see https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report

Also check the README as of 0.11.2: https://github.com/sbt/sbt-assembly/tree/0.11.2

**Comment by heitorbarbieri** [comment]
I have the same problem:

[info] Loading settings for project global-plugins from metals.sbt ...
[info] Loading global plugins from /home/heitor/.sbt/1.0/plugins
[info] Loading settings for project similardocs-build from assembly.sbt,license.sbt ...
[info] Loading project definition from /home/javaapps/sbt-projects/SimilarDocs/project
/home/javaapps/sbt-projects/SimilarDocs/build.sbt:53: error: not found: value assembly
test in assembly := {}
        ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

More info:

assembly.sbt:
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")

build.properties:
sbt.version=1.3.3

java:
openjdk version "1.8.0_232-ea"
OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

ubuntu/ intel core i5
