### ISSUE TITLE
Define settings as SettingKey, not TaskKey 

### ISSUE THREAD

**Issue by shishkin** [sbt/sbt-assembly#196]
Having `assemblyJarName` defined as `TaskKey[String]` instead of `SettingKey[String]` causes "A setting cannot depend on a task" errors when I want to use the name of the jar in a setting (for example preinitialize a console session's `initialCommands` with the info derived from the jar name).

**Comment by eed3si9n** [comment]
jar name used to be a setting but it got changed to a task here - #74

It says:

> We use git describe for jar names, so it's nice to not have to restart
> SBT after a new commit.

I don't know in the hindsight if this was a good call, but I think we're sort of stuck with this decision.
