### ISSUE TITLE
dependsOn does not work when a dependency is provided

### ISSUE THREAD

**Issue by saifellafi** [sbt/sbt-assembly#207]
Hi,

I am setting up a root project of "shared dependencies", so the sub projects dependOn this root project.

This root project has some "provided" dependencies, while others are downloaded from repo.

The thing is, that when trying to compile any of the sub projects, "provided" projects in root wont work and it will fail, not finding the classes corresponding to the provided dependencies.

I cannot afford to download the provided projects, so I am kind of stuck with this one, is this a bug or simply unimplemented feature?

This works normally if I add provided dependencies inside the build.sbt of subprojects or inside the settings of each subproject.

Thanks,
Saif

**Comment by eed3si9n** [comment]
I don't think the problem you're describing has anything to do with sbt-assembly.
Please try opening a question on Stackoverflow.

**Comment by saifellafi** [comment]
Hi, can we try to clarify? as far as I understand, "provided" idiom belongs to sbt assembly.

Thanks!
