### ISSUE TITLE
prependShellScript option results in non-portable script-JARs

### ISSUE THREAD

**Issue by naegelejd** [sbt/sbt-assembly#209]
I'm using version 0.14.3.

Because the `prependShellScript` option uses `IO.writelines`, the line terminators used in the shell script in the assembled JAR are platform-dependent. This makes the resulting script non-portable (the JAR itself is OK).

To reproduce, prepend the `defaultShellScript` **on Windows**, then execute the script/JAR on a Unix-y system.

1. Add the following to `build.sbt`:
    ```scala
    import sbtassembly.AssemblyPlugin.defaultShellScript
    assemblyOption in assembly := (assemblyOption in assembly).value.copy(prependShellScript = Some(defaultShellScript))
    ```

2. Assemble on Windows: `sbt assembly`

3. Run on Linux/OS X:
    ```
    $ ./foo-assembly-0.0.1.jar
    : No such file or directory
    ```

I understand that a simple solution would be to assemble on the target platform, but this isn't always practical.

**Comment by eed3si9n** [comment]
> the line terminators used in the shell script

gaaa. Would you like to send us a pull request on this?

**Comment by naegelejd** [comment]
I should be able to make a PR sometime in the next week. I'll have to think about the best solution. Do you have an opinion on the expected behavior?

Current behavior: The generated shell script + JAR uses platform-dependent line endings.

Potential options (lowest to highest complexity):

1. Change shell script type from `Seq[String]` to just `String`?
1. Always use `LF` terminators (Unix-like, since `sh` scripts are usually run on Unix-like systems)?
1. Make the line terminators configurable?
1. ??

**Comment by eed3si9n** [comment]
Assuming Unix-like systems sounds like a good start, at least to fix your problem.

**Comment by naegelejd** [comment]
Do you have a developer guide or any hints about the following errors I'm seeing when running `scripted` tests?

1. Repo errors:
    ```
    [info] Resolving org.eclipse.jgit#org.eclipse.jgit-parent;3.7.0.201502260915-r ...
    [warn] Host repo.lessis.me not found. url=http://repo.lessis.me/org/eclipse/jgit/org.eclipse.jgit-parent/3.7.0.201502260915-r/org.eclipse.jgit-parent-3.7.0.201502260915-r.jar
    [info] You probably access the destination server through a proxy server that is not well configured.
    [error] Server access Error: Connection timed out url=http://repo.codahale.com/org/eclipse/jgit/org.eclipse.jgit-parent/3.7.0.201502260915-r/org.eclipse.jgit-parent-3.7.0.201502260915-r.jar
    ```

2. Errors compiling scala-2.9.1.final compiler-interface (I'm using Java 1.8.0_73):
    ```
    [info] [info] 'compiler-interface' not yet compiled for Scala 2.9.1.final. Compiling...
    [error] error: error while loading CharSequence, class file '/usr/java/jdk1.8.0_73/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
    [error] (bad constant pool tag 15 at byte 1501)
    [error] error: error while loading AnnotatedElement, class file '/usr/java/jdk1.8.0_73/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
    [error] (bad constant pool tag 15 at byte 2713)
    [error] error: error while loading Arrays, class file '/usr/java/jdk1.8.0_73/jre/lib/rt.jar(java/util/Arrays.class)' isbroken
    [error] (bad constant pool tag 15 at byte 12821)
    [error] error: error while loading Comparator, class file '/usr/java/jdk1.8.0_73/jre/lib/rt.jar(java/util/Comparator.class)' is broken
    [error] (bad constant pool tag 15 at byte 5003)
    [error] /tmp/sbt_92966ec6/xsbt/ExtractAPI.scala:479: error: java.util.Comparator does not take type parameters
    [error]   private[this] val sortClasses = new Comparator[Symbol] {
    [error]                                       ^
    [error] 5 errors found
    [info] [error] (compile:compileIncremental) Error compiling sbt component 'compiler-interface'
    [info] [error] Total time: 6 s, completed Apr 29, 2016 6:36:31 PM
    ```

**Comment by eed3si9n** [comment]
We should remove ls-sbt related stuff. If you want you can make a pull request without passing test, and I can clean up the rest.
