### ISSUE TITLE
How to *totally* remove MANIFEST.MF file from generated deps file

### ISSUE THREAD

**Issue by axos88** [sbt/sbt-assembly#211]
I am generating the dependency fat jar using assemblyPackageDependency.
I am trying to determine wether the dependency needs to be synchronized based on the generated jars hash sum, however when increasing the version string, the generated manifest.mf is changed, thus triggers a large upload, although the contents of the jar do not necessarily change.

How can the META-INF/Manifest.MF be totally removed?

Using a mergeStrategy only removes consequent files, but one of them will end up in the output anywys.

**Comment by axos88** [comment]
I am trying to work around by issuing a zip -d <jar> META-INF/Manifest.MF currently, but that's hacky.

**Comment by eed3si9n** [comment]
It's created by the packing process, so I'm going to close this as won't fix.
