### ISSUE TITLE
How can i assemble all classes to a single fat jar for projects with dependence

### ISSUE THREAD

**Issue by sword865** [sbt/sbt-assembly#226]
I can't figure out how to assemble a fat jar for a project that aggregates and depends on many other projects.
For example, I have:

`lazy val a = project in file("project-a")`
`lazy val b = (project in file("project-b")).dependsOn(a)`

After sbt assembly, b-assembly.jar did not include scala classes in project a.

Thanks for help.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md 

> For questions and specific support issues use stackoverflow with tags sbt and sbt-assembly.
