### ISSUE TITLE
 unresolved dependency: com.eed3si9n#sbt-assembly;0.14.4: not found

### ISSUE THREAD

**Issue by falltodis** [sbt/sbt-assembly#239]
scala_version :2.12.1
sbt_version : 0.13.13

I added the repo "http://dl.bintray.com/sbt/sbt-plugin-releases" with 
```
resolvers += Resolver.url("bintray-sbt-plugins", url("http://dl.bintray.com/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)

```
but not works!

**Comment by fabianmurariu** [comment]
```bash
[warn] Host repo.scala-sbt.org not found. url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] 	module not found: com.eed3si9n#sbt-assembly;0.14.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.10_0.13/0.14.3/sbt-assembly-0.14.3.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.eed3si9n:sbt-assembly:0.14.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.eed3si9n:sbt-assembly:0.14.3 (scalaVersion=2.10, sbtVersion=0.13) ```

It doesn't seem to be there anymore

**Comment by eed3si9n** [comment]
https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.4/ivys/

Maybe there was an outage on Bintray?

**Comment by minhhahl** [comment]
It still happen

**Comment by rduffield** [comment]
I am seeing the same thing.
```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found
```
It's trying to access https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.10_0.13/0.14.3/sbt-assembly-0.14.3.pom which doesn't exist.

I don't see a directory for sbt-assembly beyond Scala 2.9 in https://repo1.maven.org/maven2/com/eed3si9n/.

**Comment by nsmuffin** [comment]
Same thing here

> [error] (*:update) sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.1: not found
> [error] unresolved dependency: com.eed3si9n#sbt-buildinfo;0.3.2: not found
> [error] unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
> [error] unresolved dependency: com.typesafe.sbt#sbt-twirl;1.0.3: not found
> [error] unresolved dependency: org.scoverage#sbt-scoverage;1.1.0: not found
> [error] unresolved dependency: com.eed3si9n#sbt-unidoc;0.3.2: not found
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by jfgosselin** [comment]
same problem here

      
      [warn] ==== bintray-sbt-plugins: tried
      [warn]   http://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.4/ivys/ivy.xml
      [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
      [warn]  ::          UNRESOLVED DEPENDENCIES         ::
      [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
      [warn]  :: com.eed3si9n#sbt-assembly;0.14.4: not found
      [warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by levismiller** [comment]
I get a 403 Forbidden error ... 

https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.4/ivys/ivy.xml

**Comment by london-coder** [comment]
Hi,
Since an sbt update to 0.13.15 (today 20/4/2017), I've had the same error in a project that was previously working with sbt-assembly!

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

I've tried adding the assmbly.sbt but that does not work either. If all references to assembly are removed, including assembly.sbt, sbt behaves normally

**Comment by axhm3a** [comment]
i hit the same issue, with 0.13.15.

**Comment by tianyuyao** [comment]
I meet the same issue when I was pretending package my project which was needed the third party dependencies, I created the file named "assembly.sbt", which contents `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")` . when I refresh my project:
`[info] Loading project definition from G:\ideaWorkSpace\sbttest\project
[error] Server access Error: Connection timed out: connect url=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] problem while downloading module descriptor: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml: Connection timed out: connect (21012ms)
[warn] 	module not found: com.eed3si9n#sbt-assembly;0.14.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   E:\sbtRepositories\.ivy2\local\com.eed3si9n\sbt-assembly\scala_2.10\sbt_0.13\0.14.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.10_0.13/0.14.3/sbt-assembly-0.14.3.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   E:\sbtRepositories\.sbt\boot\preloaded\com.eed3si9n\sbt-assembly\0.14.3\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/E:/sbtRepositories/.sbt/boot/preloaded/com/eed3si9n/sbt-assembly_2.10_0.13/0.14.3/sbt-assembly-0.14.3.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.14.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.eed3si9n:sbt-assembly:0.14.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.eed3si9n:sbt-assembly:0.14.3 (scalaVersion=2.10, sbtVersion=0.13) (G:\ideaWorkSpace\sbttest\project\assembly.sbt#L1-2)
[warn] 		  +- default:sbttest-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found
Invalid response.
Invalid response.
Invalid response.
Invalid response.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0`

**Comment by LinuxIsCool** [comment]
I'm having the same issue. I tried adding the following to plugins.sbt:
    resolvers += Resolver.url("bintray-sbt-plugins", url("http://dl.bintray.com/sbt/sbt-plugin-releases"))
    (Resolver.ivyStylePatterns)
and changing scalaVersion to 2.12 in build.sbt and running the following command:
    set scalaVersion := 2.12
I am still getting:
    sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found

**Comment by reddypidugu** [comment]
If you are in behind the proxy(corporate network)
For windows :
In sbt installation folder, go to conf/sbtconfig.txt file just add the following lines and save and try.

```
    -Dhttp.proxyHost=proxy
    -Dhttp.proxyPort=portno
    -Dhttp.proxyUser=UserId
    -Dhttp.proxyPassword=Password
    
    -Dhttps.proxyHost=proxyhost
    -Dhttps.proxyPort=portno 
    -Dhttps.proxyUser=UserId
    -Dhttps.proxyPassword=Password
```

For Linux/Unix:

`  export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=proxyHost  -Dhttp.proxyPort=proxyPortNumber -Dhttp.proxyUser=UserId -Dhttp.proxyPassword=Password -Dhttps.proxyHost=proxyHost -Dhttps.proxyPort=proxyPortNumber  -Dhttps.proxyUser=UserId -Dhttps.proxyPassword=Password"`

It worked for me.

**Comment by thomasdziedzic** [comment]
Figured out the issue for me, I ran `sbt -v` and saw `-Dsbt.override.build.repos=true`

I then checked `sbt -help` and found that it mentioned a file `/usr/local/etc/sbtopts` that adds some extra options to the runner. I removed the line with `-Dsbt.override.build.repos=true` and the resolver was able to find the plugin again.

**Comment by shao82456** [comment]
+1

**Comment by victorsodres** [comment]
Hello, I've just added the nexte line on `my_project/project/assembly.sbt`

     addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")

I don't know if is the right place at all, but it worked, I get the available version here:
https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/

The version that I was using was `0.14.1` dont even exists anymore
