### ISSUE TITLE
Req: Guidance on publishing a plugin for this plugin

### ISSUE THREAD

**Issue by mal** [sbt/sbt-assembly#242]
We recently had need to assemble a project that included `log4j2` and several of it's plugins. As each of those projects contain a `Log4j2Plugins.dat` cache file, we saw a bunch of conflicts. To remedy this we created a [MergeStrategy](https://github.com/idio/sbt-assembly-log4j2).

We're now investigating publishing this strategy for others to use, but wondered if there were already some conventions in place for publishing additional `MergeStrategy` classes. Also, being relatively new to this process, any other advice on naming conventions, where to publish plugins or anything else you might consider helpful would be hugely appreciated.

Many thanks 😄

**Comment by eed3si9n** [comment]
I don't know of any conventions around this. I think the most straight forward way would be publish it as a sbt plugin.

1. (optional) We recommend moving plugins to sbt organization so it's easier to add maintainers later. This is completely optional for now.
2. Publish to a personal Bintray account and request to link to sbt community repo - http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html
3. Include the plugin to plugin list - https://github.com/sbt/website#attention-plugin-authors
4. Send us a PR to describe the plugin from sbt-assembly's README.

**Comment by mal** [comment]
Thanks very much for your help! 😁 

I've gotten the first experimental release up and usable on bintray, and have submitted PRs for inclusion on the website (as you know!) and in the `sbt-assembly` README. I'll hold off on submitting it to the community repo proper until we can bump it to 1.0, after we've used it a bit more internally and written some tests for it. I'll also raise the issue of transfering it to the `sbt` org. Thanks again!
