### ISSUE TITLE
support Java 9 with sbt 0.13?

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-assembly#244]
sbt-assembly does not work with Java 9 due to parallel collection and `scala.util.Properties.isJavaAtLeast`
(same as scala-js https://github.com/scala-js/scala-js/issues/2798 )

**Comment by eed3si9n** [comment]
Maybe we provide some fallback when we detect Java 9.

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala/blob/v2.10.7/src/library/scala/util/Properties.scala#L176-L209
- https://github.com/scala/scala/commit/0259b94219c27856552c7ef00a620451c7a4cefc

workaround:
`sbt -Dsbt.scala.version=2.10.7`

**Comment by xuwei-k** [comment]
sbt 0.13.17 released. I'm closing
