### ISSUE TITLE
Use `com.typesafe.sbt` as the artifact group id

### ISSUE THREAD

**Issue by evacchi** [sbt/sbt-assembly#247]
Minor annoyance: I always forget how `eed3si9n` is spelt :P 
Moreover, most plugins in the `sbt` github organization already fall under `com.typesafe.sbt`

**Comment by eed3si9n** [comment]
> Moreover, most plugins in the sbt github organization already fall under com.typesafe.sbt

Given that most of the plugins are not actively maintained by Lightbend (e.g. sbt-native-packager), I would say we should go the opposite direction and give them some other group id to distinguish them from the artifacts that Lightbend maintains.

http://www.scala-sbt.org/0.13/docs/Community-Plugins.html:
> The sbt organization is available for use by any sbt plugin. Developers who contribute their plugins into the community organization will still retain control over their repository and its access. The goal of the sbt organization is to organize sbt software into one central location.

As noted above, sbt GitHub organization is open to hosting plugins created by community members, and I made sbt-assembly by forking Coda Hale's assembly-sbt in 2011 long before joining Lightbend.

**Comment by andreaTP** [comment]
Si @evacchi lo stato è pessimo https://github.com/sbt/sbt-release/issues/196
