### ISSUE TITLE
"Shading" randomly failed, where maybe the problem 

### ISSUE THREAD

**Issue by lserlohn** [sbt/sbt-assembly#248]
I shade some jars like that:

**********************
assemblyShadeRules in assembly ++= Seq(
  ShadeRule.rename("org.apache.curator.**" -> "mycurator.@1").inAll
)
************************

When I launch the myassembly.jar on the cluster, it randomly failed (maybe on some particular nodes). It still load from org.apache.curator, not mycurator.**)

I couldn't figure out where the problem is? 

Is this due to different version of scala, sbt or something else?

**Comment by manuzhang** [comment]
Have you checked the classpath of your process ? Is it possible there are some old unshaded jars on those nodes ?

**Comment by eric-poitras** [comment]
Probably fix this one. Please see my PR: https://github.com/sbt/sbt-assembly/pull/376

**Comment by eed3si9n** [comment]
Fixed in #376
