### ISSUE TITLE
Excluding standard scala library doesn't work

### ISSUE THREAD

**Issue by sergeda** [sbt/sbt-assembly#249]
I use 0.14.4 version of sbt-assembly.
In my build.sbt I have
```
assemblyOption in assembly := (assemblyOption in assembly).value.copy(cacheUnzip = false)

assemblyExcludedJars in assembly := {
  val cp = (fullClasspath in assembly).value
  cp filter {f => f.data.getName.startsWith("scala-")}
}

assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
```
Even so inside resulting jar there is a directory scala with all the standard classes.
How come?
Is this my mistake or bug?

**Comment by sergeda** [comment]
I have found the cause of the problem.
When I add this line 
`"com.crealytics" % "spark-excel_2.11" % "0.8.3"`
to the project dependencies "includeScala" option stops to work and there is scala lib in result jar.
Why is this so?

**Comment by manuzhang** [comment]
I checked out the `spark-excel_2.11-0.8.3.jar` and found that the scala library is assembled in it. That's why it escapes both `assemblyExcludedJars` and `includeScala`.

**Comment by sergeda** [comment]
Thanks. I've got it
