### ISSUE TITLE
multiply assembly outputs

### ISSUE THREAD

**Issue by mm12333** [sbt/sbt-assembly#255]
hi all,

is it possible generate a few output jars with assembly? 

for example:

```sbt
assemblyJarName in assembly := s"example-assembly.jar"
```

i want to build 2 jars: 

1. example-assembly.jar

2. example-assembly-latest.jar

is it possible?

**Comment by hochgi** [comment]
https://stackoverflow.com/questions/18611316/multiple-executable-jar-files-with-different-external-dependencies-from-a-single/18628906#18628906

**Comment by ryan-williams** [comment]
The above SO is >4yrs old and targets SBT 0.13.0.

This is something I've wanted to do and haven't seen a good example for doing so.

If anyone has advice I'd be interested to hear it!

**Comment by hochgi** [comment]
@ryan-williams The only difference is that now, instead of:
```
import AssemblyKeys._
```
you should simply `.enablePlugins(AssemblyPlugin)`
