### ISSUE TITLE
JCE cannot authenticate the provider BC` when running a JAR with assembly

### ISSUE THREAD

**Issue by fbiswt** [sbt/sbt-assembly#257]
In my scala project I use "org.bouncycastle" % "bcprov-jdk14" % "1.51" for cryptography.
If it test my project in Scala IDE it works fine. But once I make a JAR and try to run it via java -jar ... it throws an exception: Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC

This is a issue in stackoverflow, I met the same issue, I think this is assembly plugin's problem.

**Comment by eed3si9n** [comment]
It's not a plugin problem. Please see the answer on Stackoverflow -https://stackoverflow.com/a/13726570/3827

**Comment by prayagupd** [comment]
the solution can be to [provide the `bcprov-*.jar` via `-classpath`](https://stackoverflow.com/a/50226284/432903)

```bash
java -cp chat-server.jar:/Users/prayagupd/.ivy2/cache/org.bouncycastle/bcprov-ext-jdk16/jars/bcprov-ext-jdk16-1.46.jar com.chat.server.ChatServer
```
