### ISSUE TITLE
`sbt assembly` with shading not working properly inside docker container

### ISSUE THREAD

**Issue by stevenchen3** [sbt/sbt-assembly#259]
Recently, I encountered an issue regarding `sbt assembly` with shading over `shapeless` inside Docker container. When run `sbt assembly` inside Linux Docker container (tested on CentOS 7, 7.1, 7.3 and Ubuntu 16.04) to package the project, the following error message showed, resulting in the Jar unfunctional with Spark (which is similar to [this](https://stackoverflow.com/questions/36406750/shading-over-third-party-classes) StackOverflow ticket).

```shell
Fully-qualified classname does not match jar entry:
  jar entry: shapeless/$tilde$qmark$greater$?.class
  class name: shapeless/$tilde$qmark$greater$?.class
Omitting shapeless/$tilde$qmark$greater$?.class.
```

Look like `sbt assembly` shading some library does not exist in `shapeless`???? Went through related issues on the Internet, even though changing shading rule to what is listed as follows also won't work.

```shell
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("shapeless.**" -> "shaded_shapeless.@1").inAll
)
```

The SBT version is 0.13.8 (tried 0.13.15 as well) and `sbt-assembly` version is `1.4.5`. However, when running `sbt assembly` on bare metal machines (tested on CentOS 7, 7.1, 7.3 and macOS Sierra), it works just fine.

Not sure if there's something going with my settings or it might be a bug or incompatibility issue with `sbt-assembly`.  You can reproduce this issue by using [https://github.com/stevenchen3/sbt-assembly-inside-docker](https://github.com/stevenchen3/sbt-assembly-inside-docker)

**Comment by stevenchen3** [comment]
Updates:

This is not an issue with `sbt-assembly`. It is mainly because of the difference of `NAME_MAX` between bare metal and docker container. And it can be fixed by adding the following to `build.sbt`

```shell
scalacOptions ++= Seq("-Xmax-classfile-name","255")
```

**Comment by stevenchen3** [comment]
Tried workarounds raised [here](https://github.com/sbt/sbt-assembly/issues/69), it's not working.

**Comment by LeifW** [comment]
We're hitting this too. SBT 0.13.12, sbt-assembly 0.14.3. Bumped those t0 0.13.15 and 0.14.5 respectively, still happens.

Also, it would be nice to have it error and abort in this scenario, instead of continuing on and successfully delivering a broken jar to you.

**Comment by stevenchen3** [comment]
For my case, this is not caused by `sbt-assembly`. It is because of the Unicode support issue in docker image you use. Make sure the locale config enables Unicode support in your docker container. 

But @LeifW has a point that it would be nice to abort the assembly task, rather generating a broken jar. ;)

**Comment by LeifW** [comment]
I was using the 1science/sbt image.
Doing `export LANG=C.UTF-8` fixed the issue for me - thanks for the pointer!

**Comment by jayadeepj** [comment]
I have the same issue inside Docker container and SBT version 0.13.11 & 0.13.15. Doing export LANG=C.UTF-8 doesn't seem to resolve the issue for me. The shapeless shade gives me a broken jar

**Comment by liubov-dmitrieva** [comment]
Have exactly the same problem on Red Hat Enterprise Linux Server release 6.8 (Santiago).

On mac it is working.  export LANG=C.UTF-8 doesn't seem to resolve the issue for me.

```
Renamed shapeless/Default$$anon$1.class -> shadeshapeless/Default$$anon$1.class
Fully-qualified classname does not match jar entry:
  jar entry: shapeless/$tilde$qmark$greater$?.class
  class name: shapeless/$tilde$qmark$greater$?.class
Omitting shapeless/$tilde$qmark$greater$?.class.
Removed shapeless/$tilde$qmark$greater$?.class
```

**Comment by liubov-dmitrieva** [comment]
No, the export works!
I've done  export LANG=en_GB.UTF-8

**Comment by jayadeepj** [comment]
I had to do 

localedef -i en_US -f UTF-8 en_US.UTF-8
export LANG=en_US.UTF-8

on Mac OS X El Capitan (version 10.11) running Docker container (CentOS 7) and SBT version 0.13.11 / 0.13.15

**Comment by arun0009** [comment]
any updates on this? I have the same issue

**Comment by stevenchen3** [comment]
@arun0009  This workaround (https://github.com/stevenchen3/sbt-assembly-inside-docker) fixes my issue. You might give it a try.

**Comment by mt40** [comment]
I'm using CentOS 7 and this works for me
```
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
```

**Comment by ericdotdata** [comment]
I think this issue can be closed, adding: `ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en" LC_ALL="en_US.UTF-8"` into your `Dockerfile` (or any `UTF-8`) will fix this.
