### ISSUE TITLE
Unresolved dependency generating jar with SBT

### ISSUE THREAD

**Issue by antoniocachuan** [sbt/sbt-assembly#276]
I'm developing a Spark process in Scala (Eclipse IDE) and runs fine in my local pc, but when I try to compiled with SBT that I installed on my pc I got a error (see picture).

My first doubt is why SBT try to compile with scala 2.12 if I explicitly set scalaVersion to 2.11.11 in my build.sbt. I tried installing other SBT versions with the same results, also in other PCs but not works. I need help to fix it.

scala_version(Spark) :2.11.11
sbt_version : 1.0.2
spark: 2.2
**build.sbt**

```
name := "Completitudf"
version := "1.0"
organization := "com.bcp.spark"
scalaVersion := "2.11.11"
libraryDependencies ++= Seq(
"org.apache.spark" %% "spark-core" % "2.2.0" % "provided",
"org.apache.spark" %% "spark-sql" % "2.2.0" % "provided"
)
```
**assembly.sbt**

`addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.0.2")`

![error](https://user-images.githubusercontent.com/4010332/32244673-4e034872-be47-11e7-9833-440dabf34634.png)

**Comment by eed3si9n** [comment]
Try

```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
```
