### ISSUE TITLE
sbt-assembly not working

### ISSUE THREAD

**Issue by ysule** [sbt/sbt-assembly#277]
Hi I have followed every way suggested by the community but I cant get my SBT assembly plugin to work.
I have created assembly.sbt file in project directory, use the same addSbtPlugin option in my plugins.sbt file. but still I cant get it to work,
IDE : IntelliJ  IDEA CS
Scala = 2.11.11,211.8(tested on both)
sbt = 0.13.16
Any sort of help would be appreciated

**Comment by EnverOsmanov** [comment]
(I think you should use stackoverflow.com if you looking for a solution to **your** question.)

Any error messages? What happens when you type `sbt assembly`?

**Comment by EnverOsmanov** [comment]
@reddybhavaniprasad

1) Why you are not using stackoverflow.com for this kind of questions?
2) Please run `sbt assembly` in your project's directory. Not in default root's directory.

**Comment by reddybhavaniprasad** [comment]
Thanks for the reply. 

I tried running "sbt assembly" from the project's directory still faced the same issue.

The issue is due to version mismatch of sbt-assembly. sbt with >1.0 versions need a sbt-assembly 0.14.6 versions and above. Now, it is working fine.
