### ISSUE TITLE
[Question] Assembling fat jar with unmanagedJars only

### ISSUE THREAD

**Issue by l15k4** [sbt/sbt-assembly#281]
Hey,
I'm having hard times assembling a jar that would contain nothing else but my project + unmanagedJars : 
```
assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false, includeDependency = false, includeBin = true),
addArtifact(Artifact("qkit", "assembly"), sbtassembly.AssemblyKeys.assembly),
```
It always contains all dependencies.

**Comment by eed3si9n** [comment]
Please use Stackoverflow for questions - https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
