### ISSUE TITLE
reduce the logging?

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-assembly#290]
it would be good if lines like

```
 log.info("Including: %s".format(jarName))
```

and so on were debug level, because they are very noisy in CI and rarely useful on-going interactive information.

In addition, I feel the warning logs like

```
[warn] Merging 'scala/tools/nsc/doc/html/resource/lib/type_diagram.png' with strategy 'discard'
```

should also be `debug` level. I get hundreds of these.

**Note from Eugene**:
Vote :+1: to remove default logging and turn it to debug level, :-1: to keep default logging.

**Comment by fommil** [comment]
dupe of #272?

**Comment by eed3si9n** [comment]
Merging is an anomaly that shouldn't happen if each JAR didn't have duplicates, so I think it makes sense to output logs at warn or info level. You can opt out of logs as follows:

```scala
    logLevel in assembly := Level.Error,
```

**Comment by fommil** [comment]
It's not an anomaly if you've explicitly asked for that merge strategy.

**Comment by eed3si9n** [comment]
The strategies that are generating the logs would not know if they've been applied by your custom rules or by a built-in strategy choice.

Maybe ppl can vote 👍 or 👎  on this issue.

**Comment by lunaryorn** [comment]
The output helped at least once to catch a major dependency issue in our builds; I’m all in favour of keeping it.

**Comment by fommil** [comment]
How about built in strategies use higher logging and user ones use lower logs? My PR also reduces incremental log messages to DEBUG.
