### ISSUE TITLE
consider changing the default of "test in assembly"

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-assembly#292]
I would guess that the **vast majority** of `sbt-assembly` users do not want tests to run when building the assembly jar, so `test in assembly := {}` would be a far more appropriate default. Let those who have crazy build pipelines customise their setup.

**Note from Eugene**:
Vote :+1: to remove default testing, :-1: to keep default testing.

**Comment by eed3si9n** [comment]
Let's take a poll on this one too.

**Comment by paulp** [comment]
Are tests automatically run for `sbt package`? What's different about assembly? I get an unpleasant paternalistic vibe from build tools which run the tests automatically even when I'm doing something unrelated to running the tests.

**Comment by eed3si9n** [comment]
I blindly followed this behavior when I ported assembly-sbt to sbt 0.10. Maybe the tradition goes back to Maven's assembly.

One _potential_ reason one may add this task dependency is that if someone is trying to compose deployment as a task, the person might want `assembly` to run strictly after testing is done.

In any case I do agree on the paternalistic vibe.

**Comment by fommil** [comment]
the ayes have it

**Comment by eed3si9n** [comment]
> the ayes have it

Confirmed.
