### ISSUE TITLE
Shading spark libraries doesn't work... 

### ISSUE THREAD

**Issue by gravitywp** [sbt/sbt-assembly#296]
Shading only changed the package structure, didn't change declared package name. in other word, didn't rewrite bytecodes.
![image](https://user-images.githubusercontent.com/8477504/34860469-96351f28-f798-11e7-91bd-8cb087a570a0.png)
![image](https://user-images.githubusercontent.com/8477504/34860480-a40aea88-f798-11e7-9319-17a069713587.png)

**Comment by parikhv15** [comment]
I am facing the same issue with jackson-module-scala.

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_2.11</artifactId>
            <version>2.8.8</version>
        </dependency>

**Comment by grant-guo** [comment]
I met the similar issue with libraries written by scala. However when I added the shaded jar to Bytecode viewer, i can see everything is changed. But seems Intellij can't see the changes.
I also tried to shade a pure java library, it worked.

**Comment by naderghanbari** [comment]
I'm facing the same thing. It works for Java libraries but when I try to shade `akka-stream-kafka` (a Scala library) it doesn't work. This is the error I get:

This is the shading rule

```scala
ShadeRule.rename("akka.kafka.**" -> "shadedakkakafka.@1").inLibrary(AkkaStreamKafka),
```

and this is the compile error I get when using the shaded jar in another project:

```
Symbol 'term akka.kafka' is missing from the classpath.
```

**Comment by eed3si9n** [comment]
Shading based on jarjar links does not affect the Scala pickles, so it needs to be done all the way at the end. I doesn't work for libraries in general, Spark or otherwise.

**Comment by cchantep** [comment]
@eed3si9n Thx for the feedback. What would be the suggestion to properly shade a Scala lib?
