### ISSUE TITLE
Provide a setting to exclude Scala library

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt-assembly#3]
If one plans to execute the jar with the scala command (instead of Java), then it's not necessary to include the Scala library.

**Comment by matanster** [comment]
Thanks this feature is really helpful

**Comment by chadvoegele** [comment]
For anyone else who ends up here, the syntax changed to: 
`assembleArtifact in packageScala := false`

**Comment by angelcervera** [comment]
Changed again to:
`assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)`

**Comment by liubov-dmitrieva** [comment]
I need to exclude scala if I am compiling for running my jar with spark and leave it if I will run locally.
Is there a better way than to comment / uncomment the line every time? Something like introduce custom parameter for sbt assembly?
```
assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
```

**Comment by radhe-kishan** [comment]
What is the newer syntax for this?
