### ISSUE TITLE
sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.6: not found

### ISSUE THREAD

**Issue by ashu2012** [sbt/sbt-assembly#309]
build.sbt:-

name := "scalaReadingFromxlsheet"

version := "0.1"

scalaVersion := "2.12.4"

//assemblySettings

resolvers += Resolver.bintrayIvyRepo("com.eed3si9n", "sbt-plugins")

libraryDependencies ++= Seq(
  "org.apache.poi" % "poi-ooxml" % "3.11",
  "org.apache.poi" % "poi" % "3.11",
  "org.scalatest" %% "scalatest" % "3.0.1" % Test ,
"com.eed3si9n" % "sbt-assembly" % "0.14.6"

)
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")

initialCommands in console += " import org.apache.poi._"

exportJars := true

mainClass in Compile := Some("readxls")
mainClass in(Compile, run) := Some("readxls")
mainClass in(Compile, packageBin) := Some("readxls")

**Comment by ashu2012** [comment]
sbt version 1.1.1

C:\Users\h217119\IdeaProjects>sbt about
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[warn] No sbt.version set in project/build.properties, base directory: C:\Users\h217119\IdeaProjects
[info] Set current project to ideaprojects (in build file:/C:/Users/h217119/IdeaProjects/)
[info] This is sbt 1.1.1
[info] The current project is ProjectRef(uri("file:/C:/Users/h217119/IdeaProjects/"), "ideaprojects") 0.1.0-SNAPSHOT
[info] The current project is built against Scala 2.12.4
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.4

**Comment by realrunner** [comment]
I'm seeing this too. Did you ever find a workaround?

```
::::::::::::::::::::::::::::::::::::::::::::::
::          UNRESOLVED DEPENDENCIES         ::
::::::::::::::::::::::::::::::::::::::::::::::
:: com.eed3si9n#sbt-assembly;0.14.3: not found
::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by eed3si9n** [comment]
Yes. It should be `Resolver.sbtPluginRepo("releases")`, which should be already part of sbt's metabuild.
