### ISSUE TITLE
Urgent - Which version of SBT and assembly to use for scala 2.11.8 (spark 2.2.1)

### ISSUE THREAD

**Issue by AbdullahServantOfAllah** [sbt/sbt-assembly#311]
Please provide sample configuration files that is a working set.

**Comment by EnverOsmanov** [comment]
Any version is fine. For example in my project **sbt** `0.13.17` and **sbt-assembly** `0.14.6`.

(Please use [stackoverflow.com](https://stackoverflow.com) for such questions)
