### ISSUE TITLE
No output jar produced, even when output claims success.

### ISSUE THREAD

**Issue by thunderkid** [sbt/sbt-assembly#323]
Running `sbt assembly` is claiming that the assembly jar is up to date, but it's producing no jar. (And it's producing no errors in the output - just merge warnings):
```
....
[warn] Merging 'io\netty\util\internal\shaded\org\jctools\queues\atomic\MpscAtomicArrayQueue.class' with strategy 'first
'
[warn] Merging 'io\netty\util\internal\shaded\org\jctools\queues\atomic\SpscLinkedAtomicQueue.class' with strategy 'firs
t'
[warn] Merging 'io\netty\util\internal\shaded\org\jctools\util\Pow2.class' with strategy 'first'
[warn] Merging 'io\netty\util\internal\shaded\org\jctools\util\UnsafeAccess.class' with strategy 'first'
[warn] Merging 'io\netty\util\internal\shaded\org\jctools\util\UnsafeRefArrayAccess.class' with strategy 'first'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to 311 files
[warn] Strategy 'filterDistinctLines' was applied to a file
[warn] Strategy 'first' was applied to 1488 files
[info] Assembly up to date: C:\mypath\target\scala-2.12\myjar.jar
[success] Total time: 33 s, completed Jun 15, 2018 11:54:39 AM
```
There's no jar file produced at this location. This seems to be related to my adding `circe` to `build.sbt` - before adding `circe` it was working fine. Presumably there's some shading or something I need to fiddle around with. But it's pretty hard to debug when no errors are given and `sbt-assembly` falsely claims the jar file is up to date.

**Comment by eed3si9n** [comment]
Hi. Thanks for the report.
Could you outline the reproduction steps please?

1. assembly
2. add circe
3. assembly

?

**Comment by kietay** [comment]
@thunderkid ever figure this one out? 😆

**Comment by thunderkid** [comment]
@kietay 
It's been a while, but as I recall, this bug was the final tricky thing that led me to abandon `sbt-assembly`. It had always been very fiddly for me since you had to constantly worry about dependencies interfering with each other, guessing which version to force manually, and hoping your choice didn't break anything. When this particular problem came up I switched over to using `sbt pack`. There was an hour or so of pain in adjusting some of my AWS deployment scripts, and since then `sbt pack` has always worked fine for me. No more conflict issues.

**Comment by kellanburket** [comment]
I ran into this same issue and it turned out to be a java heap issue. Assembly fails silently then reports the out of memory error to the debug log `[debug] java.lang.OutOfMemoryError: Java heap space`. The fix was to adjust the sbt heap size: `SBT_OPTS=-Xmx2G`.
