### ISSUE TITLE
Log dependent jar file sizes

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt-assembly#326]
It would be useful if we log jar file sizes during assembly. Often times we observe result jars with enormous sizes and would like to know which dependent jar cause the bloating in size

**Comment by eed3si9n** [comment]
It seems like the general opinion about sbt-assembly is it should reduce the logs, not increase it. https://github.com/sbt/sbt-assembly/issues/290
I am closing this for now.
