### ISSUE TITLE
Help with really old scala code

### ISSUE THREAD

**Issue by CAROLZXYZXY** [sbt/sbt-assembly#331]
Hi,

I am trying to build a scala project, which is written in 2013. When I am using the 'sbt publish-local', it turns out to have the error: 
Note: Unresolved dependencies path:
[warn]          com.eed3si9n:sbt-assembly:0.8.7 (scalaVersion=2.12, sbtVersion=1.0) (/home/xinyi/TextRayRoot/openie-backend/project/plugins.sbt#L1-2)
[warn]            +- default:openie-backend-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.8.7: not found

When I change the plugins.sbt into addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.7"), it turns out that  
[error] /home/xinyi/TextRayRoot/openie-backend/project/Build.scala:4:20: object Plugin is not a member of package sbtassembly

How can I solve it?
BTW, I am building openie-backend project.

Thanks a lot!

**Comment by eed3si9n** [comment]
I think you need to specify `sbt.version` in `project/build.properties` file. Try:

```
sbt.version=0.13.17
```

Currently it's trying to start up as sbt 1.x.

**Comment by eed3si9n** [comment]
This is likely no longer a "bug" with sbt-assembly, so maybe you could get more help elsewhere, like Gitter chat for scala/scala. Good luck, and have a nice weekend.
