### ISSUE TITLE
Avoid scalastyle check as part assembly

### ISSUE THREAD

**Issue by adi2ky** [sbt/sbt-assembly#341]
Hey guys,

my build.sbt has following statements to execute scalastyle check as part of compilation:
`lazy val compileScalastyle = taskKey[Unit]("compileScalastyle")
compileScalastyle := scalastyle.in(Compile).toTask("").value
(Keys.compile in Compile) := ((Keys.compile in Compile) dependsOn compileScalastyle).value`

How do I avoid this scalastyle during assembly phase like when i run `assemblyPackageDependency`

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
