### ISSUE TITLE
How to publish a fat jar

### ISSUE THREAD

**Issue by Mvpanswer7** [sbt/sbt-assembly#342]
How to config the build.sbt file in order to publish a fat jar made by assembly plugin?
I tried but command `publish` will open push a thin jar onto my configured repo, not the fat jar

**Comment by ryan-williams** [comment]
fwiw I have [an SBT plugin](https://github.com/hammerlab/sbt-parent/tree/93922c52af51a4bfb1d7de7c31ca00dd6a37a2a4/assembly) that wraps this one with a few relevant configurations:
- [`publishAssemblyJar`](https://github.com/hammerlab/sbt-parent/blob/assembly-4.6.2/assembly/src/main/scala/org/hammerlab/sbt/plugin/Assembly.scala#L122): include the uber JAR with `shaded` classifier in published artifacts ([example](https://github.com/hammerlab/spark-bam/blob/1.2.0-M1/build.sbt#L112))
- [`publishThinShadedJar `](https://github.com/hammerlab/sbt-parent/blob/assembly-4.6.2/assembly/src/main/scala/org/hammerlab/sbt/plugin/Assembly.scala#L44):
  - create a "thin" shaded JAR that only includes specific dependencies (those in [`shadedDeps`](https://github.com/hammerlab/sbt-parent/blob/assembly-4.6.2/assembly/src/main/scala/org/hammerlab/sbt/plugin/Assembly.scala#L23))
  - publish that shaded JAR _instead of_ the usual JAR as the default, no-classifier artifact
  - the implementation on this one is a bit tedious and brittle, and indicates room for improvement (in this plugin and possibly my wrapper), but it's worked for my purposes to date ([example](https://github.com/hammerlab/genomic-loci/blob/2.0.4/build.sbt#L21-L29))

Either of those terms can be dropped into a `build.sbt`

**Comment by eed3si9n** [comment]
See https://github.com/sbt/sbt-assembly#publishing-not-recommended
