### ISSUE TITLE
fail "merging/merging" scripted test in travis-ci since December 2018

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-assembly#356]
🤔 

https://travis-ci.org/sbt/sbt-assembly/jobs/478647768#L882

```
[info] [error] java.lang.Exception: file /tmp/sbt_419bffc2/a had wrong content:
[info] [error] 2
[info] [error] 1
[info] [error] 3
[info] [error] 1
[info] [error] *** instead of ***
[info] [error] 1
[info] [error] 2
[info] [error] 1
[info] [error] 3
[info] [error] 	at $94426f8c8ad71399f0ed$.mustContain(build.sbt:48)
[info] [error] 	at $94426f8c8ad71399f0ed$.$anonfun$testmerge$7(build.sbt:21)
[info] [error] 	at $94426f8c8ad71399f0ed$.$anonfun$testmerge$7$adapted(build.sbt:19)
[info] [error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:475)
```

https://travis-ci.org/sbt/sbt-assembly/builds

<img width="960" alt="travis-ci-build-logs" src="https://user-images.githubusercontent.com/389787/51070477-555b0280-1685-11e9-8130-1cbe85faabda.png">

https://github.com/sbt/sbt-assembly/commits/master

<img width="525" alt="master-branch-commit-log" src="https://user-images.githubusercontent.com/389787/51070490-90f5cc80-1685-11e9-8e7c-267b1256f954.png">

**Comment by eed3si9n** [comment]
I guess it makes sense to sort.
