### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by MohamedSMahmoud** [sbt/sbt-assembly#358]
Hi ,
 i'm using bcprov-jdk15on-161b24.jar  and bctls-jdk15on-161b24.jar with apache-tomcat-6.0.43 and JDK 1.5 under RedHat 6.9
while I'm trying to call a web service a got an error "JCE cannot authenticate the provider BC"
kindly help me to find a solution to this issue

**Comment by eed3si9n** [comment]
Hi. We use GitHub issue mostly to track bugs and tasks. For questions and specific support issues please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sbt-assembly) with tags `sbt` and `sbt-assembly`. See https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
