### ISSUE TITLE
MergeStrategy does not work for duplicate META-INF/io.netty.versions.properties

### ISSUE THREAD

**Issue by nextdtinc** [sbt/sbt-assembly#362]
no merge strategy works to eliminate this issue:

    io.netty/netty-codec-http/jars/netty-codec-http-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-codec/jars/netty-codec-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-transport/jars/netty-transport-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-buffer/jars/netty-buffer-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-common/jars/netty-common-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-resolver/jars/netty-resolver-4.1.17.Final.jar:META-INF/io.netty.versions.properties
    io.netty/netty-handler/jars/netty-handler-4.1.17.Final.jar:META-INF/io.netty.versions.properties

    assemblyMergeStrategy in assembly := {
     case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
     case "META-INF/io.netty.versions.properties" => MergeStrategy.first
     case x => MergeStrategy.first
    }

**Comment by saurabhkolte** [comment]
Was this resolved?

**Comment by psilos** [comment]
@nextdtinc what was the solution to this?

**Comment by aspektr** [comment]
1. use:
`case "META-INF/io.netty.versions.properties" => MergeStrategy.first`
2. in sbt shell:
     `clean`
      `reload`

**Comment by alphaho** [comment]
I have run into the same issue on windows but unluckily found this issue has been closed.

After spending some time on this, I think the correct solution is to replace the line

```scala
case "META-INF/io.netty.versions.properties" => MergeStrategy.first
```

with:

```scala
case PathList("META-INF", "io.netty.versions.properties") => MergeStrategy.first
```


Putting it together, it will be:

```scala
assemblyMergeStrategy in assembly := {
 case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
 case PathList("META-INF", "io.netty.versions.properties") => MergeStrategy.first
 case x => MergeStrategy.first
}
```

**Comment by shonfeder** [comment]
Does anyone know why this workaround is needed?

**Comment by shonfeder** [comment]
As a note for future seekers, the following worked to resolve the issue for me, and seemed more focused to me than discarding the `MANIFEST.MF` :)

```scala
      assembly / assemblyMergeStrategy := {
        // Workaround for conflict with grpc-netty manifest files
        // See https://github.com/sbt/sbt-assembly/issues/362
        case PathList("META-INF", "io.netty.versions.properties") => MergeStrategy.first
        case x                                                    => (assembly / assemblyMergeStrategy).value(x)
      },

```

Also see https://stackoverflow.com/a/67343619/1187277
