### ISSUE TITLE
Release 1.14.10?

### ISSUE THREAD

**Issue by avdv** [sbt/sbt-assembly#378]
Hi.

The latest release on github + tag says `1.14.10`, but you probably meant `0.14.10`...

**Comment by dejan2609** [comment]
Version **0.14.10** is published to Bintray few days ago:

![image](https://user-images.githubusercontent.com/19467899/61061545-baa56b80-a3fc-11e9-8cf3-9044ff25474d.png)

**Comment by eed3si9n** [comment]
oh oops. it seems like I created a wrong tag / release, but correct version - http://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.10/

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-assembly/releases/tag/v0.14.10
