### ISSUE TITLE
Scala 2.13 excluding scala-xml

### ISSUE THREAD

**Issue by abhamjee** [sbt/sbt-assembly#380]
With Scala 2.13, the libraries scala-xml, scala-parser-combinators and a few others are no longer included in the official distribution. If I add these libraries to my project as dependencies, sbt-assembly is excluding them in the function Assembly.isScalaLibraryFile.

**Comment by eed3si9n** [comment]
I had forgotten this myself but https://github.com/sbt/sbt-assembly#excluding-scala-library-jars says:

> To exclude Scala library (JARs that start with `scala-` and are included in the binary Scala distribution) to run with scala command,

so by that admission criteria, I agree with the expectation of this issue.
