### ISSUE TITLE
[Question] How to skip assembly when dependencies haven't changed

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-assembly#386]
I have a plugin that uses `sbt-assembly` as a dependency of creating a Python `.whl`.  during development and testing of the `.whl`, the assembly process reruns every time, even if none of the Scala code or other dependencies have changed. Is there some way to have `sbt-assembly` skip rebuilding the assembly in this case? IOW, only run the full process when its dependencies have changed?

**Comment by eed3si9n** [comment]
Is this a question or a feature request? (All questions are redirected to Stackoverflow per [guideline](https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md))

I think some parts are cached, but maybe not fully.

**Comment by metasim** [comment]
> Is this a question or a feature request?
🤷‍♂ is calling `assembly` twice in a row supposed to bypass building the second time? In our configuration that's not happening, so if it's supposed to do that and isn't, it's either a) a bug for me to report, or b) an SO question on which switch I'm not seeing in the docs, or c) a feature request.

**Comment by eed3si9n** [comment]
>  is calling assembly twice in a row supposed to bypass building the second time?

https://github.com/sbt/sbt-assembly/blob/edd35cfbaf05c3465371b63d38fda8ac579d766c/src/main/scala/sbtassembly/Assembly.scala#L92-L103

Looking at the code, I think it's supposed to cache if nothing changed.

```
sbt:hello> clean
[success] Total time: 0 s, completed Oct 11, 2019 4:39:27 PM
sbt:hello> assembly
[info] Compiling 1 Java source to /Users/eed3si9n/work/hellotest/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /Users/eed3si9n/work/hellotest/target/scala-2.12/test-classes ...
[info] foo.SomethingTest
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Strategy 'discard' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'rename' was applied to 2 files (Run the task at debug level to see details)
[success] Total time: 4 s, completed Oct 11, 2019 4:39:34 PM
sbt:hello> assembly
[info] foo.SomethingTest
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Strategy 'discard' was applied to a file (Run the task at debug level to see details)
[info] Assembly up to date: /Users/eed3si9n/work/hellotest/target/scala-2.12/hello-assembly-0.1.0-SNAPSHOT.jar
[success] Total time: 0 s, completed Oct 11, 2019 4:39:39 PM
```

**Comment by metasim** [comment]
Thanks for your help. I think the problem I had was that I'm using `sbt-buildinfo` (with a build date in it), so technically the source changes every time, triggering the rebuild. I appreciate you looking into it!
