### ISSUE TITLE
sbt-assembly dependency error

### ISSUE THREAD

**Issue by rakesh-an1992** [sbt/sbt-assembly#387]
I'm receiving the below error, when I'm trying use sbt-assembly plugin for scala project.
unable to get resource for com.eed3si9n#sbt-assembly;0.14.5: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.5/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.5: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.5/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Here is the version details :
Scala : 2.11.8
Spark : 2.3.1
sbt : 1.2.8
sbt-assembly : 0.14.5

**Comment by eed3si9n** [comment]
It looks like your HTTPS certificate is unable to validate https://repo.typesafe.com/ according to the error message.
