### ISSUE TITLE
Alphabetical classpath order breaks compatibilty for MergeStrategy 

### ISSUE THREAD

**Issue by atais** [sbt/sbt-assembly#389]
Hello.

I have updated the plugin to `0.14.10` after using old `0.14.6` version for some time in one of my projects and I was really surprised to find differences in assembled jar files 

It turned out that #356 #357 fixes some builds, but breaks others.

I have spent quite some time on understanding the `MergeStrategy` mechanism and the classpath order which I believe is inherited from Maven. My findings are summed up [HERE](https://github.com/atais/mvn-sbt-assembly), maybe your comment on it could clarify my misunderstandings.

Anyways, currently, I am really confused with the merging mechanism which fails on my project structured like this:

```
project-A
 /src/main/resources/META-INF/persistence.xml

project-B
 /src/main/resources/META-INF/persistence.xml

projectB.dependsOn(projectA).settings{
   ...
  case x if x.contains("persistence.xml") => MergeStrategy.first
   ...
}
```

Before `0.14.10` assembling `project-B` resulted with `persistence.xml` being sourced from `project-B`. With `0.14.10`, since `project-A` is first, alphabetically, it copies one from there.

I think previous order was based on some kind of dependency-graph-tree, which resulted in order being equal to some "depth". However now... it will be nearly impossible to pick the right file.
Imagine if `project-C` comes to play. How should I pick the middle file?

Currently, I would vote for reverting this change.
But what do you guys think?

Thanks a lot!

**Comment by eed3si9n** [comment]
Apache Ivy used to return the modules in topological order, but I don't think Coursier does (yet)?
See https://github.com/coursier/coursier/issues/1466 and https://github.com/sbt/sbt/issues/5282.

I think depending on any sort of classpath ordering is unreliable, and my opinion is that you should make your own MergeStrategy for this, which might sound difficult, but I don't think it's bad. See the implementation of `MergeStrategy.first` for example:

```scala
  val first: MergeStrategy = new MergeStrategy {
    val name = "first"
    def apply(tempDir: File, path: String, files: Seq[File]): Either[String, Seq[(File, String)]] =
      Right(Seq(files.head -> path))
  }
```

The main part is a single line.

**Comment by atais** [comment]
I understand that relying on dependency order may not sound like a silver bullet for merging files during the assembly process. However, I believe this may be a bigger issue for some (like me) and frankly, I don't think writing my own `MergeStrategy` should be necessary. Also, the old mechanism was here for years, especially since it was compatible with `Maven` so if one new how it works you could have find your way using `first` and `last` pretty easy.

I think that changing that behaviour on your side should be followed up by new handlers (strategies). Maybe one that could allow the user to select the file by project name? Or some path matcher? I believe this would be beneficial for all if you'd reopen the issue.

Thanks!
