### ISSUE TITLE
Skipping tests

### ISSUE THREAD

**Issue by daltyboy11** [sbt/sbt-assembly#394]
Hi, when I add `test in assembly := {}` to my `build.sbt` file I get the following when I run `sbt assembly`:

```
error: not found: value assembly
test in assembly := {}
           ^
```

Where are you supposed to insert `test in assembly := {}`?

**Comment by eed3si9n** [comment]
Hi, if you have questions about how to use sbt-assembly please use Stackoverflow - https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
