### ISSUE TITLE
Question about assemblyExcludedJars

### ISSUE THREAD

**Issue by matanster** [sbt/sbt-assembly#396]
I have a jar I'm adding to a project, that does not have to be part of the assembly:

> "com.google.cloud" % "google-cloud-storage" % "1.107.0"

When I exclude it using the following code idiom:

```
    assemblyExcludedJars in assembly := {
        val cp = (fullClasspath in assembly).value
        cp filter { f => f.data.getName.contains("google-cloud-storage") }
      },
```
I get a merge error which I would not get when this dependency is not added:

> deduplicate: different file contents found in the following

I suspect that either the `assemblyExcludedJars` handling doesn't take effect early enough, yielding a collision that may come from transitive dependencies of this jar, or possibly that `assemblyExcludedJars` does not apply transitively (meaning that it does not exclude transitive dependencies of the dependencies provided to it). 

I'd be very thankful for clarification on this aspect! 

Many thanks!

> sbt.version = 0.13.16

**Comment by eed3si9n** [comment]
I think there's a bug in readme examples. Could you try:

```scala
assemblyExcludedJars in (Compile, assembly) := ....
```

**Comment by eed3si9n** [comment]
Check `assembly:: assemblyExcludedJars` and see if it's actually hitting a JAR I guess.
If you have further questions, please open a Stackoverflow question.
https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
