### ISSUE TITLE
Version 0.15.0 is not released to Bintray

### ISSUE THREAD

**Issue by zzvara** [sbt/sbt-assembly#399]
Should it be here? https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/

**Comment by zzvara** [comment]
Only sources are available now: https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.15.0/

**Comment by PenBarker** [comment]
Looks like 0.14.10 has gone missing in the process?

**Comment by eed3si9n** [comment]
I tried to unlink and link, but sync seems to be broken on Bintray side for 0.15.0.

**Comment by leifwickland** [comment]
I came here to report the same issue. Thanks for working on it, @eed3si9n.

**Comment by eed3si9n** [comment]
I have reported this to Bintray, and got a confirmation from the frontline support person around 10h ago saying

> I will further check with the internal team regarding the missing files and I will get back to you with an update at the earliest.

so the ball is bouncing on Bintray's court.

**Comment by anilkumarmyla** [comment]
Maybe release 0.15.1 and throw away 0.15.0?

**Comment by eed3si9n** [comment]
Should be fixed now.

**Comment by fancywriter** [comment]
Hey @eed3si9n 
Currently this link https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/ gives 403 forbidden for me.

**Comment by fancywriter** [comment]
Could it be related to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter ?
