### ISSUE TITLE
How do you specify/figure out which minimum JDK is required for running the fat jar?

### ISSUE THREAD

**Issue by karanveersp** [sbt/sbt-assembly#404]
I used sbt-assembly on a project where I have some java 14 jars, and my local machine has JDK 8 as the default JDK.

The `sbt assembly` task was successful and produced a fat jar.

When I run it with JDK 8, I get the error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/event/EventTarget has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
JDK 11 (version 55.0) is the one I need. And sure enough, when I set JDK 11 on my shell, I can run the fat jar.

Is there a way to be explicit about the target JDK version in the `build.sbt` file?
Also, I'm surprised that even though I have Java 14 jars in the dependency, the application runs fine on JDK 11. Is it just an example of Java's supreme backwards compatibility in action? I would like to know what else could be at work.

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and discuss feature or bugs on sbt-assembly. If you have questions regarding sbt-assembly please check this out - https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md
