### ISSUE TITLE
Facing deduplicate assembly errors

### ISSUE THREAD

**Issue by vvavepacket** [sbt/sbt-assembly#413]
Why is this assembly tool throws a lot of deduplicate errors like these

```
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[error] 1123 errors were encountered during merge
[error] stack trace is suppressed; run last assembly for the full output
[error] (assembly) deduplicate: different file contents found in the following:
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-dynamodb/1.11.655/aws-java-sdk-dynamodb-1.11.655.jar:.gitkeep
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/istack/istack-commons-runtime/3.0.8/istack-commons-runtime-3.0.8.jar:.gitkeep
[error] deduplicate: different file contents found in the following:
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-all/4.1.51.Final/netty-all-4.1.51.Final.jar:META-INF/native-image/io.netty/common/native-image.properties
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.42.Final/netty-common-4.1.42.Final.jar:META-INF/native-image/io.netty/common/native-image.properties
[error] deduplicate: different file contents found in the following:
```
There are like 1123 errors and there's no way we can manually merge each of the conflicting files...

But in Java, when I use Maven's assembly / jar packager, it just doesn't throw them. Scala and Java is based using the JVM but I just dont understand why this assembly tool is having that issue?

**Comment by KhankaLake** [comment]
If the default MergeStrategy.deduplicate is not working for you, that likely means you have multiple versions of some library pulled by your dependency graph. The real solution is to fix that dependency graph.



zhangdaolin@ieslab.cn
 
From: Ivan Matala
Date: 2021-02-03 10:52
To: sbt/sbt-assembly
CC: Subscribed
Subject: [sbt/sbt-assembly] Facing deduplicate assembly errors (#413)
Why is this assembly tool throws a lot of deduplicate errors like these
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[error] 1123 errors were encountered during merge
[error] stack trace is suppressed; run last assembly for the full output
[error] (assembly) deduplicate: different file contents found in the following:
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-dynamodb/1.11.655/aws-java-sdk-dynamodb-1.11.655.jar:.gitkeep
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/istack/istack-commons-runtime/3.0.8/istack-commons-runtime-3.0.8.jar:.gitkeep
[error] deduplicate: different file contents found in the following:
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-all/4.1.51.Final/netty-all-4.1.51.Final.jar:META-INF/native-image/io.netty/common/native-image.properties
[error] /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.42.Final/netty-common-4.1.42.Final.jar:META-INF/native-image/io.netty/common/native-image.properties
[error] deduplicate: different file contents found in the following:

There are like 1123 errors and there's no way we can manually merge each of the conflicting files...
But in Java, when I use Maven's assembly / jar packager, it just doesn't throw them. Scala and Java is based using the JVM but I just dont understand why this assembly tool is having that issue?

**Comment by eed3si9n** [comment]
All sbt-assembly is doing is unzipping and zipping back again. When you have overlapping content in your dependency graph like netty-all vs netty-common sbt-assembly will detect that as error because it assumes that you want to know these duplicate situation as error. If you don't care that you might have erroneous classpath, you can go ahead and use `MergeStrategy.first`.

Other alternative if you don't want to deduplicate things is to use sbt-native-packager or sbt-onejar.
