### ISSUE TITLE
Change group name from `com.eed3si9n` to `com.sbt` or equivalent 

### ISSUE THREAD

**Issue by nerkka** [sbt/sbt-assembly#416]
I was looking for an _official_ `sbt-assembly` plugin and landed on this page. However, the group name `com.eed3si9n` looks very unofficial to me. Hoping to see a more official like group name is possible in the future release.

**Comment by eed3si9n** [comment]
What does official mean? The one published by me is the de facto standard.

**Comment by nerkka** [comment]
> What does official mean? The one published by me is the de facto standard.

Well, you should mention this in your README and explain why the group name is not 'com.sbt'.

**Comment by nerkka** [comment]
> What does official mean? The one published by me is the de facto standard.

Also explain why the copy right looks like this. 
'Copyright (c) 2010-2014 e.e d3si9n, Coda Hale'

**Comment by eed3si9n** [comment]
sbt plugins in general are mostly maintained by individual volunteers. I really don't understand why I owe you an explanation on what the `organization` my plugin uses.

**Comment by nerkka** [comment]
Lmao, it's forcefully closed without any explanations. This is why people should never, don't even bother to, use any unofficial libraries for any production applications.

**Comment by nerkka** [comment]
![Screen Shot 2021-02-23 at 8 03 40 PM](https://user-images.githubusercontent.com/50816881/108945889-4c81dc80-7612-11eb-9bfd-22c51faadb2b.png)
I suggest you to learn from them, instead of owning a `personal` project to satisfy your own ego.

**Comment by SethTisue** [comment]
scientists have identified a new, more virulent form of the Open Source Entitlement virus and wish to warn the public that the mutation be spreading in the wild

**Comment by Kevin-Lee** [comment]
> I suggest you to learn from them, instead of owning a `personal` project to satisfy your own ego.

??? learn from them?! 🤔  Sure you should learn from Eugene.
He spends his life on OpenSource projects so that people like you and me can use them.

![Screen Shot 2021-02-26 at 12 20 09 am](https://user-images.githubusercontent.com/2307335/109160228-a1b41e80-77c9-11eb-8442-9640e73a9091.png)
![Screen Shot 2021-02-26 at 12 20 29 am](https://user-images.githubusercontent.com/2307335/109160236-a4af0f00-77c9-11eb-9d44-9372e813ecd7.png)

**Comment by nerkka** [comment]
@Kevin-Lee Sure, I appreciate his efforts on this. Sure, tons of open source projects are developed and maintained by individual volunteers. 

But for this particular one, `sbt-assembly`, "The one published by me is the de facto standard." ??? By "me", really? What I saw was a fork from an old repo, and has dozens of other great engineers also made contribution. 

I should learn from Eugene for what? Taking the entire credit, and even put my own name on the `organization` of a OPEN SOURCE PROJECT to advertise myself?

**Comment by eed3si9n** [comment]
> (By the way, I'm not using this plugin unless the organization name changes. I'm pretty sure there's shit tons of people out there also hesitate of using any unofficial libraries.)

sbt-assembly is an unofficial library maintained by one person. No one else is merging pull requests, or cutting releases. If the organization name reflects that and makes people uncomfortable, I think I've communicated the situation fine.

Also in general, sbt-assembly should not be used that widely. sbt-native-packager is where it's at.
