### ISSUE TITLE
"[warn] Ignored unknown package option FixedTimestamp" since sbt 1.5.x

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-assembly#421]
## Step

run `sbt assembly` with sbt 1.5.0-RC2, sbt-assembly 0.15.0

## Note

https://github.com/sbt/sbt/pull/6237

**Comment by AnirudhVyas** [comment]
Still getting this issue with `sbt 1.6.2`. WARN:

```scala
[warn] Ignored unknown package option FixedTimestamp(Some(1262304000000))
```
