### ISSUE TITLE
Unable to download SBT-assembly 0.14.x due to jitpack build failures

### ISSUE THREAD

**Issue by nvander1** [sbt/sbt-assembly#424]
All of the four latest releases of sbt assembly 0.14.x on jitpack give an error about not being able to resolve dependency on sbt 0.13.x

- https://jitpack.io/com/github/sbt/sbt-assembly/v0.14.10/build.log
- https://jitpack.io/com/github/sbt/sbt-assembly/v0.14.9/build.log
-  https://jitpack.io/com/github/sbt/sbt-assembly/v0.14.8/build.log
- https://jitpack.io/com/github/sbt/sbt-assembly/v0.14.7/build.log

@eed3si9n @xuwei-k @rjmac @jeroentervoorde

**Comment by cperriard** [comment]
Is this due to bintray brown-out? Are there plans to migrate from bintray? Thanks!

**Comment by frankivo** [comment]
See #425
