### ISSUE TITLE
Unable to download dependencies: Error downloading com.eed3si9n:sbt-assembly;sbtVersion=1.0;scalaVersion=2.12:0.14.9

### ISSUE THREAD

**Issue by glarkou** [sbt/sbt-assembly#425]
I think the issue is related to the announcement here -> https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We have to publish the plugin somewhere else. 

[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.eed3si9n:sbt-assembly:0.14.9 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.typesafe.sbt:sbt-git:1.0.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.typesafe.sbt:sbt-native-packager:1.3.15 (sbtVersion=1.0, scalaVersion=2.12)

**Comment by opendatakraken** [comment]
This could happen because the bintray jcenter public repository has been discontinued:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by opendatakraken** [comment]
Is it possible to publish the packages directly here? https://github.com/orgs/sbt/packages

**Comment by dnzprmksz** [comment]
Same here, blocking the build. Any workarounds? Seems like related to the sunset. 🌆

**Comment by fpopic** [comment]
@opendatakraken maybe better to the maven central repo? @eed3si9n

**Comment by riccardocorbella** [comment]
Build blocked also here...

**Comment by frankivo** [comment]
> Same here, blocking the build. Any workarounds? Seems like related to the sunset. 🌆

I tried to build sbt-assembly locally, but that also has failing dependencies (https://github.com/sbt/sbt-pgp) now.

**Comment by FreddieSanchez** [comment]
FYI - This is a brown out caused by bintray to alert users to switch: https://status.bintray.com/

> Schedule brown-out session on April 12th 6AM to 2PM Pacific Daylight Time
In progress - Scheduled maintenance is currently in progress. We will provide updates as necessary.
Apr 12, 13:00 UTC
Scheduled - Scheduled brown-out session to warn users about May 1st as sunset date for Bintray.
>
> Artifactory installations with remote repositories configured against JCenter, GoCenter and ChartCenter will not be affected by this sunset.
> 
>We recommend that JFrog Cloud customers continue using jcenter.bintray.com, gocenter.io, and repo.chartcenter.io as Artifactory remote repositories going forward.
> 
> JFrog self-hosted customers can also continue fetching from these repositories, but are encouraged to migrate to the canonical repositories.
> 
> Additional details can be found at https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by kgupta26** [comment]
Same here. Following packages are experiencing 403

https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager
https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly
https://dl.bintray.com/sbt/sbt-plugin-releases/com.cavorite/sbt-avro
https://dl.bintray.com/sbt/sbt-plugin-releases/com.thesamet/sbt-protoc
https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp

Even though I have not mentioned anywhere in my resolver section of build.sbt to go to Bintray, why does it?

**Comment by riccardocorbella** [comment]
Thanks @FreddieSanchez! So if I understand correctly it should be available again at 2 p.m. PDT.
Based on this [tweet](https://twitter.com/eed3si9n/status/1381627420927782916?s=20), @eed3si9n is already aware that Bintray will be dismissed in favour of JFrog.
@eed3si9n have you already opened some issue so we can help you with the migration and hopefully finish before the 1st of May?

**Comment by FreddieSanchez** [comment]
> Thanks @FreddieSanchez! So if I understand correctly it should be available again at 2 p.m. PDT.

That is my understanding.

**Comment by riccardocorbella** [comment]
This issue relates to [sbt#6294](https://github.com/sbt/sbt/issues/6294)

**Comment by eed3si9n** [comment]
Yea. Please see https://github.com/sbt/sbt/issues/6294. It will be back again in a few hours.
