### ISSUE TITLE
sbt assembly not available on Bintray

### ISSUE THREAD

**Issue by jornfranke** [sbt/sbt-assembly#428]
Bintray is sunset and thus the sbt assembly plugin is not available:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Would it be possible to publish it on Maven central? 
https://central.sonatype.org/publish/publish-guide/

thank you.

**Comment by eed3si9n** [comment]
Eventually a new version will be available on Maven Central but all the existing versions are still at https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/.

We changed the underlying implementation of repo.scala-sbt.org from Bintray to Artifactory -  
https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1
