### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by dziemba** [sbt/sbt-assembly#429]
Hey @eed3si9n, 
sorry to bother you like this, but I'd really love to try out the new [Fixed Timestamp feature](https://github.com/sbt/sbt-assembly/pull/422). 
Any chance we can get a new released version soon?
Thanks! 🙂

**Comment by eed3si9n** [comment]
I'll try to get to it this weekend.

**Comment by eed3si9n** [comment]
Done - https://eed3si9n.com/sbt-assembly-1.0.0

**Comment by dziemba** [comment]
Thank you! ❤️
