### ISSUE TITLE
Warn: sbt-assembly-1.1.0.jar no longer exists

### ISSUE THREAD

**Issue by pascalsasger** [sbt/sbt-assembly#451]
I keep receiving this warning:

```
sbt-assembly-1.1.0.jar no longer exists exists at /root/.cache/coursier/v1/https/repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/1.1.0/sbt-assembly-1.1.0.jar
```

sbt version - 1.5.5 with sbt-assembly 1.1.0

Anyone knows how to resolve this?

**Comment by eed3si9n** [comment]
Hi. We use GitHub issue mostly to track bugs and tasks. For questions and specific support issues please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sbt-assembly) with tags `sbt` and `sbt-assembly`. See https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report
