### ISSUE TITLE
Apparently ignored settings in 2.0.0-RC1

### ISSUE THREAD

**Issue by benhutchison** [sbt/sbt-assembly#469]
Just want to note Im seeing case where a project works fine with 1.2.0 and same config doesnt work with 2.0.0-RC1.

No main class is emitted into the manifest with 2.0.0-RC1. 

Its a subproject, nothing too unusual, with a line like:

`assembly / mainClass := Some("serverbot.Serverbot"),`

in its settings. Other assembly settings are also ignored, such as the jar name.

**Comment by fnqista** [comment]
Hey man, I was the contributor for 2.0.0-RC1, but I never touched the sbt scoped settings (well, I deleted some, but none related to the main class or the jar name). 

I would like to help when I have time - can you provide more details - a sample sbt project in github would help a lot. If that is too much, just try to provide your redacted build.sbt and some more info like is it a multi-module project, the sbt version used, etc

**Comment by benhutchison** [comment]
fwiw I just flipped back to 2.0.0-RC1 and the main class entry vanished, then back to 1.2 again and it reappeared.

I'll do a manual inspect of the diffs between 1.2 and 2 and see if I find any clues, then try to make a repro example

**Comment by benhutchison** [comment]
Now it's working fine in 1.2 and 2!? Not sure whats going on.. Someone can reopen if they encounter similar.

**Comment by coderfromhere** [comment]
I'm seeing this error right now with `2.1.1`
