### ISSUE TITLE
Current alternative to assembledMappings

### ISSUE THREAD

**Issue by OndrejSpanel** [sbt/sbt-assembly#497]
In #227 it is described how to add additional files using `assembledMappings`. This key no longer exists since 2.0.0. The change does not seem to be mentioned in the release notes. How can I add new files to the JAR in 2.0.0 and newer?

**Comment by tdroxler** [comment]
hi everyone!

Ping for this one :)

Thx

**Comment by jelmerk** [comment]
curious about this too

**Comment by eed3si9n** [comment]
Here's my answer from 2013 - https://stackoverflow.com/a/18773471/3827

**Comment by OndrejSpanel** [comment]
It was often used to add files which were built by sbt, located in target somewhere - see https://github.com/sbt/sbt-assembly/issues/227#issuecomment-283504401. I am afraid "putting" such files in lib is not possible.

**Comment by eed3si9n** [comment]
ok I guess we can consolidate this issue into #227 then?

**Comment by OndrejSpanel** [comment]
Sure, no problem. (For the record: I personally do not use or miss this functionality at the moment)
