### ISSUE TITLE
addSbtPlugin("com.eed3si9n" % "sbt-assembly ... fails with Error downloading com.eed3si9n:sbt-assembly...

### ISSUE THREAD

**Issue by devosalain** [sbt/sbt-assembly#542]
addSbtPlugin("com.eed3si9n" % "sbt-assembly ... fails with Error downloading com.eed3si9n:sbt-assembly...

**Comment by eed3si9n** [comment]
Hi. We use GitHub issue mostly to track bugs and tasks. For questions and specific support issues please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sbt-assembly) with tags `sbt` and `sbt-assembly`, and hopefully someone could come along and help you. See https://github.com/sbt/sbt-assembly/blob/master/CONTRIBUTING.md#where-to-file-a-bug-report. There's also a Discord channel, often used for sbt Q&A linked from https://www.scala-sbt.org/community
