### ISSUE TITLE
Can't figure out how to specify a main class.

### ISSUE THREAD

**Issue by hartleys** [sbt/sbt-assembly#61]
I'm sure I must be doing something wrong, but I can't for the life of me figure out what. I've stripped it down to as simple as possible, but it still doesn't work.

I keep getting this error when I try to run the jar files:

<pre>
Error: Could not find or load main class runner.runner
</pre>

The build.sbt and plugins.sbt files were exactly as in your example at:
https://github.com/sbt/sbt-assembly
except build.sbt is:

<pre>
import AssemblyKeys._
assemblySettings
jarName in assembly := "MyScalaUtils.jar"
mainClass in assembly := Some("runner.runner")
</pre>

Here's my src directory layout:

<pre>
$ ls -R src
src:
helloWorldTest  runner

src/helloWorldTest:
helloWorld.scala

src/runner:
runner.scala
</pre>

runner.scala is just:

<pre>
package runner

class runner {
  def main(args: Array[String]){
    println("Starting run.");
    helloWorldTest.helloWorld.run(args);
    println("Done.");
  }
}
</pre>

What the heck is going wrong here?

**Comment by yishenggudou** [comment]
I Got this error too

**Comment by kindlychung** [comment]
Same issue here. 

`java -jar` complains about main class not found, `java -cp x.jar path.to.Main` works.

**Comment by nob13** [comment]
> Same issue here.
> 
> `java -jar` complains about main class not found, `java -cp x.jar path.to.Main` works.

For google: Perhaps it's a problem like this: https://stackoverflow.com/a/46287790
