### ISSUE TITLE
packaging takes very long time

### ISSUE THREAD

**Issue by pankajmi** [sbt/sbt-assembly#68]
I am not sure if I am the only one who is facing this problem but 
Packaging takes hell lot of time. May be I am missing some settings or something.
Last these three steps are the slowest, build stucks here for long long time.

```
[info] Merging 'org/apache/http/annotation/Immutable.class' with strategy 'deduplicate'
[info] SHA-1: WrappedArray(26, -125, -113, 64, 37, 94, -6, -79, -79, 41, 34, -92, 42, 7, -72, 31, -97, -57, 55, -2)
[info] Packaging ~/workspace/myproj/xyz/target/xyz-assembly-1.0.jar ..
[info] Done packaging.
[success] Total time: 724 s, completed 31 Jan, 2013 1:51:10 PM
```

Please let me know if anyone need more info ?

**Comment by fblundun** [comment]
@joeroot I have the same issue of `sbt assembly` taking much longer in a VirtualBox guest (even with access to all cores) than the host. Did you ever find a way around this?

**Comment by iangelov** [comment]
That's probably because disk i/o is more expensive inside a VM (those files need to be read in order to determine their SHA1 hashes)

**Comment by joeroot** [comment]
@fblundun: I never found a way around this, instead I run `set assembly` from within Mac, which is slightly frustrating.

@iangelov: It could be i/o, but that seems quite extreme. My projects don't have that many files, and I tend to end up crashing, rather than completing very slowly.

**Comment by eed3si9n** [comment]
One idea that was suggested by @jsuereth was that sbt-assembly try reading into the JAR directly without unzipping first. ymmv/pr welcome on this front.

**Comment by jramos** [comment]
If you're using `vboxfs` (the Vagrant default) there's no way around this. It's slow. You should use `nfs` instead.

**Comment by AnirudhVyas** [comment]
@eed3si9n I have the exact same problem; my project is barebones, spark, akka, scala 2.11.8 - was there an option to disable calculation of SHA1 added?  Assembly is taking 774+ seconds
```
import Dependencies._
resolvers ++= Seq(
  Resolver.sonatypeRepo("releases"),
  Resolver.sonatypeRepo("snapshots")
)
lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "me.free",
      scalaVersion := "2.11.8",
      version := "0.1.0-SNAPSHOT"
    )),
    name := "BondAgent",
    libraryDependencies ++= Seq(akkDeps ++ Seq(scalaCheck)
      ++ Seq(shapelessDep)
      ++ sparkDeps
      ++ Seq(redisScala)
      ++ argonautDeps ++ sparkConflictResolverDeps).flatten
  )
assemblyMergeStrategy in assembly := {
  case PathList("org", "aopalliance", xs@_*) => MergeStrategy.first
  case PathList("javax", "inject", xs@_*) => MergeStrategy.first
  case PathList("javax", "servlet", xs@_*) => MergeStrategy.first
  case PathList("javax", "activation", xs@_*) => MergeStrategy.first
  case PathList("org", "xml-apis", x@_*) => MergeStrategy.first
  case PathList("javax", "stax-api", x@_*) => MergeStrategy.first
  case PathList("org", "commons-collections", x@_*) => MergeStrategy.first
  case PathList("org", "jcl-over-slf4j", x@_*) => MergeStrategy.first
  case PathList("org", "apache", xs@_*) => MergeStrategy.first
  case PathList("com", "google", xs@_*) => MergeStrategy.first
  case PathList("com", "esotericsoftware", xs@_*) => MergeStrategy.first
  case PathList("com", "codahale", xs@_*) => MergeStrategy.first
  case PathList("com", "yammer", xs@_*) => MergeStrategy.first
  case "about.html" => MergeStrategy.rename
  case PathList("META-INF", xs@_*) => MergeStrategy.discard
  case "META-INF/ECLIPSEF.RSA" => MergeStrategy.first
  case "META-INF/mailcap" => MergeStrategy.first
  case "META-INF/mimetypes.default" => MergeStrategy.first
  case "plugin.properties" => MergeStrategy.first
  case "log4j.properties" => MergeStrategy.first
  case "overview.html" => MergeStrategy.first
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}
assemblyOption in assembly := (assemblyOption in assembly).value//.copy(includeScala = false)
assemblyJarName in assembly := "BondAgent.jar"
```

This is my assembly sbt - 
```
import Versions._
import sbt._

object Dependencies {
  lazy val scalaCheck: ModuleID = "org.scalacheck" %% "scalacheck" % "1.12.2" % "test"
  lazy val akkaStream: ModuleID = "com.typesafe.akka" %% "akka-stream" % akkaStreamV
  lazy val akkaActor: ModuleID = "com.typesafe.akka" %% "akka-actor" % akkaV
  lazy val akkaSlf4j: ModuleID = "com.typesafe.akka" %% "akka-slf4j" % akkaV
  lazy val akkDeps = Seq(akkaStream, akkaActor, akkaSlf4j)
  lazy val sparkCore: ModuleID = "org.apache.spark" %% "spark-core" % sparkCoreV
  lazy val sparkSql: ModuleID = "org.apache.spark" %% "spark-sql" % sparkCoreV
  lazy val sparkDeps = Seq(sparkCore.exclude("org.eclipse.jetty.orbit", "javax.servlet").
    exclude("org.eclipse.jetty.orbit", "javax.transaction").
    exclude("org.eclipse.jetty.orbit", "javax.mail").
    exclude("org.eclipse.jetty.orbit", "javax.activation").
    exclude("commons-beanutils", "commons-beanutils-core").
    exclude("commons-collections", "commons-collections").
    exclude("commons-collections", "commons-collections").
    exclude("xml-apis", "xml-apis").
    exclude("javax.xml.stream", "stax-api")
    exclude("com.esotericsoftware.minlog", "minlog"), sparkSql.exclude("org.eclipse.jetty.orbit", "javax.servlet").
    exclude("org.eclipse.jetty.orbit", "javax.transaction").
    exclude("org.eclipse.jetty.orbit", "javax.mail").
    exclude("org.eclipse.jetty.orbit", "javax.activation").
    exclude("commons-beanutils", "commons-beanutils-core").
    exclude("commons-collections", "commons-collections").
    exclude("commons-collections", "commons-collections").
    exclude("xml-apis", "xml-apis").
    exclude("javax.xml.stream", "stax-api")
    exclude("com.esotericsoftware.minlog", "minlog"))
  lazy val funcDeps: ModuleID = "org.typelevel" %% "cats-core" % catsCoreV
  lazy val shapelessDep: ModuleID = "com.chuusai" %% "shapeless" % shapelessV
  lazy val hadoopClientDep: ModuleID = "org.apache.hadoop" % "hadoop-client" % hadoopCV
  lazy val parquetClient: ModuleID = "org.apache.parquet" % "parquet" % parquetV
  lazy val redisScala: ModuleID = "com.github.etaty" %% "rediscala" % redisScalaV
  lazy val argonautDeps: Seq[ModuleID] = Seq("io.argonaut" %% "argonaut").map(_ % argonautV)
  lazy val sparkConflictResolverDeps: Seq[ModuleID] = Seq("com.fasterxml.jackson.core" % "jackson-core" % "2.8.7",
  // test deps
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.7",
    "com.fasterxml.jackson.core" % "jackson-annotations" % "2.8.7",
    "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.8.7",
    // With spark, to resolve java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal (error)
    //"xml-apis" % "xml-apis" % "1.4.01",
    // With spark, to resolve large stack trace on java.lang.ClassNotFoundException: de.unkrig.jdisasm.Disassembler (warning)
    "org.codehaus.janino" % "janino" % "3.0.7")
}
```

Not sure how to make it fast but it is affecting my development timelines - any help, suggestions, rants are welcome...

**Comment by jramos** [comment]
@AnirudhVyas are you building in a VM?

**Comment by AnirudhVyas** [comment]
no - build on macbook os x

**Comment by eed3si9n** [comment]
@AnirudhVyas Do you have SSD drive on your MacBook?
See https://github.com/sbt/sbt-assembly#other-things, and try turning off any of the optional features and see if it helps your situation.

**Comment by AnirudhVyas** [comment]
I have an ssd, let me see thanks. Will report back...

**Comment by AnirudhVyas** [comment]
not much difference - well I gained about a 100 second if thats a consolation ... do you know where the bottleneck is? it seems to be taking a while in packaging... Honestly I have been using this awesome plugin for a while, but I never used it with spark, I used to tar up, thought I'd give it a try while putting it along with sbt on a fresh project - something is missing ...

**Comment by AnirudhVyas** [comment]
ok for now I made my app a spark submit - i was using a single package for a reason, with provided spark dependencies, less things to deal with, it completes in 180s ... very doable i think. But it would be great if know where the bottleneck was/is so that perhaps it could be improved? I am not implying that you haven't tried already - my apologies if I come across as blunt...

**Comment by eed3si9n** [comment]
I personally haven't run into performance issues so I haven't really looked at current bottlenecks. If there's some specific issue around, feel free to create a sample project that someone could look into.

**Comment by EnverOsmanov** [comment]
I've played a bit with **sbt-assembly 0.14.7-SNAPSHOT**.
Changing [this line](https://github.com/sbt/sbt-assembly/blob/d42fd96537a19ac30306cda1d033adaa8920bcfc/src/main/scala/sbtassembly/Assembly.scala#L202):
`      (for(jar <- libsFiltered.par) yield {`
to this line:
`      (for(jar <- libsFiltered) yield {`
increased packaging speed 3x times (from 1544 seconds to 571 seconds).

My fat jar is about 130 MiB. My computer has SSD. Could anyone test this solution on own project?

**Comment by EnverOsmanov** [comment]
@eed3si9n
I'm sorry, I can't share my work project. I've created [sample project](https://github.com/EnverOsmanov/sbt-assembly_TEST) using [some post](queirozf.com/entries/creating-scala-fat-jars-for-spark-on-sbt-with-sbt-assembly-plugin) from the internet. Assembly takes:
`libsFiltered.par` => 588-634 seconds
`libsFiltered` => 320-402 seconds

Fat jar size is 96 MiB.

**Comment by jrudolph** [comment]
I guess creating >60k files while unpacking puts major stress on the file system. Doing that non-sequentially by adding `par` probably makes things rather worse...

**Comment by noahlz** [comment]
hello from 2019. I had this exact problem (yes,old project old version of sbt, but still) and doing `sbt clean` followed by `assembly` solved it.

YMMV

**Comment by karthicks** [comment]
I'm on `sbt 0.12.01` and `macOS`.  Every once in a while, the `assembly` goal simply hangs on the `packaging jar` step. Will upgrading my `sbt` help?

**Comment by Sathiyarajan** [comment]
any updates on this thread it's hanging for long time in the ubuntu 18.04 LTS @karthicks @noahlz @devmanhinton ?

**Comment by noahlz** [comment]
Wowwow found my way back to this issue via google. I have no insight except trying what past me did (clean assembly)
