### ISSUE TITLE
"File name too long" error occurs when attempting to assemble a project on an encrypted Linux machine

### ISSUE THREAD

**Issue by JustAHappyKid** [sbt/sbt-assembly#69]
Sorry in advance, as this is as much an OS/file-system limitation as it is a bug in the software, but devising some sort of workaround in this plugin (sbt-assembly) would seem the most practical route.

So, this seems to occur with any project that uses the newly-released [Slick library](http://slick.typesafe.com/). This is the library-dependency line:

```
"com.typesafe.slick" %% "slick" % "1.0.0"
```

Then, when running `sbt assembly`, you get something like this:

```
[error] (*:assembly) Error extracting zip entry 'scala/slick/compiler/ReplaceFieldSymbols$$anonfun$scala$slick$compiler$ReplaceFieldSymbols$$rewrite$1$3$$anonfun$apply$3$$anonfun$apply$5$$anonfun$apply$7$$anonfun$3.class' to '/home/chris/Desktop/simple-slick/target/scala-2.10/cache/default-9a0c39/global/assembly/8529d1f5a87909bfe3ce47bceecf3c9a5d0bb40e/scala/slick/compiler/ReplaceFieldSymbols$$anonfun$scala$slick$compiler$ReplaceFieldSymbols$$rewrite$1$3$$anonfun$apply$3$$anonfun$apply$5$$anonfun$apply$7$$anonfun$3.class': java.io.FileNotFoundException: /home/chris/Desktop/simple-slick/target/scala-2.10/cache/default-9a0c39/global/assembly/8529d1f5a87909bfe3ce47bceecf3c9a5d0bb40e/scala/slick/compiler/ReplaceFieldSymbols$$anonfun$scala$slick$compiler$ReplaceFieldSymbols$$rewrite$1$3$$anonfun$apply$3$$anonfun$apply$5$$anonfun$apply$7$$anonfun$3.class (File name too long)
[error] Total time: 6 s, completed Feb 27, 2013 11:07:33 AM
```

**Comment by nickpoorman** [comment]
This isn't just encrypted machines. Docker has the limit as well. Anything that tries to use sbt-assemly in a Docker container could fail becuase of this.

**Comment by nightscape** [comment]
I'm just running into the same problem and the workarounds are not very handy...
Wouldn't it be an option if sbt-assembly just didn't write the files to disk? If it just kept them in memory (maybe via config option so it doesn't crash for large projects) and repacked them into the final jar from there then this problem wouldn't occur, right?

**Comment by adamnovak** [comment]
There's a workaround I remember I used to limit the length (although I
don't remember what it is). Maybe that length limit should be on/shorter by
default?

**Comment by nightscape** [comment]
I guess you're referring to using `-Xmax-classfile-name` as a compiler option.
Unfortunately the implicit default value for this option is 255 which is bigger than the 242 that's supported by Docker.
So in my case, I'm trying to assemble a fat jar inside a Docker container (building jars inside a Docker container greatly simplifies your build-server) which fails due to the shapeless library having file names > 242 characters.
I could locally build a shapeless version with `-Xmax-classfile-name=242`, but that would be rather annoying and not solve the larger problem...

**Comment by janstenpickle** [comment]
Just came across this from some googling and just wanted to post a workaround for anyone having the same issue, but not wanting to recompile third party libs.

I mounted a directory from the host server in the docker container using the `-v` switch, seeing as this volume is ext4 the assembly works as if it were outside docker.

[(more info about mounting directories from the host can be found in the docker docs here)](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume)

**Comment by nightscape** [comment]
Ah, good idea @janstenpickle! I tried incorporating an in-memory FS into sbt-assembly but didn't get very far.

**Comment by JonathanTaws** [comment]
Can confirm that @janstenpickle suggestion to mount the directory on the host is a perfect workaround, worked like a charm. Thank you !

**Comment by annalopezz** [comment]
I recommend using the Long Path Tool to resolve this issue.
