### ISSUE TITLE
error: not found: object AssemblyKeys

### ISSUE THREAD

**Issue by cypres2003** [sbt/sbt-assembly#71]
I'm trying to add assembly task to sbt, but when I run the reload command I get this error.
I'm using:
scala 2.10.1
sbt 0.12.2

This is my build.sbt 

``` scala
import AssemblyKeys._

seq(assemblySettings: _*)
```

This is my plugins.sbt

``` scala
resolvers += Resolver.url("sbt-plugin-releases-scalasbt", url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/"))

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.0.0")

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.8.6")
```

**Comment by sujitpal** [comment]
FWIW, its 2015 and a build.sbt for a project I hadn't worked on for a while had these lines. My current environment is Scala 2.10.4 and SBT 0.13.7 on Mac OSX 10.9.5. The build.sbt was a working one in my previous machine which had Scala 2.10.2 and SBT 0.13.1 (I think). In any case, putting this comment here in case someone else has a similar problem.

```scala
import AssemblyKeys._

assemblyKeys
```

and when trying to do a "sbt clean compile" I was getting the following error:

```console
/Users/palsujit/Projects/solr4-extras/build.sbt:1: error: not found: object AssemblyKeys
import AssemblyKeys._
       ^
/Users/palsujit/Projects/solr4-extras/build.sbt:3: error: not found: value assemblySettings
assemblySettings
    ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Removing these lines still allows you to run "assembly" from the sbt prompt. Also note that the current README.md in this project (Aug 1 2015) has no reference to these lines, so I suspect that it is no longer necessary to explicitly declare these in the build.sbt anymore as long as the plugin is registered in $PROJECT_ROOT/projects/assembly.sbt (or in ~/.sbt/0.13/plugins/plugins.sbt - thats where I have all my global plugins declared).

**Comment by eed3si9n** [comment]
@sujitpal See https://github.com/sbt/sbt-assembly/blob/master/Migration.md#upgrading-with-bare-buildsbt

**Comment by sujitpal** [comment]
Thank you that explains it. I should have looked at the migration guide.
