### ISSUE TITLE
Tags for the assembly task

### ISSUE THREAD

**Issue by hrjet** [sbt/sbt-assembly#78]
I want to restrict the number of assembly tasks that run in parallel based on the tags feature in sbt 0.12. Specifically, I want to add a large weight for `Tags.Disk`.

Is there a way to set this tag for all assembly tasks in the system?

Alternatively, what is the right syntax for setting this for a singe task? I tried something like this in build.sbt but that didn't work: 

```
assembly in myTask <<= tagw(Tags.Disk -> 4)
```

(I tried many other variations but I will skip them for brevity's sake).

A solution for all tasks or even a single task would be very helpful. Thanks in advance!

**Comment by pshirshov** [comment]
Actually, it was a good, really good idea to put a global tag on assembly task. Why didn't you do that?
