### ISSUE TITLE
Proper deduplication incantation

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-assembly#92]
I am working on a custom REPL. My build.sbt contains:

```
libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-compiler" % "2.10.2",
  "org.scala-lang" % "jline" % "2.10.2"
)
```

Running `sbt assembly` produces:

```
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /home/mslinn/.ivy2/cache/org.fusesource.jansi/jansi/jars/jansi-1.4.jar:org/fusesource/jansi/Ansi$1.class
[error] /home/mslinn/.ivy2/cache/org.scala-lang/jline/jars/jline-2.10.2.jar:org/fusesource/jansi/Ansi$1.class
```

I tried adding this to `build.sbt`:

```
mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) => { case _ => MergeStrategy.discard } }
```

That produced a whole lot of output, like this:

```
[warn] Merging 'scala/reflect/internal/Mirrors$RootsBase$$anonfun$getModuleOrClass$1.class' with strategy 'discard'
[warn] Strategy 'discard' was applied to 15671 files
```

Seems the dependencies might be expressed better, or a different deduplication strategy should be used. I am pretty sure that jline is a compiler dependency, so there must be a way to tell sbt-assembly to use that version instead of hauling in a new dependency. Suggestions?

**Comment by channingwalton** [comment]
I've just run into this but my issue is that we have an unmanaged jar with libjansi.so. None of the above options are working, I cannot find a way to exclude it at all. Here is a sample error

```
[error] /Users/waltocha/dev/projects/elderberry/dmz/lib/jboss-cli-client.jar:META-INF/native/linux32/libjansi.so
[error] /Users/waltocha/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.7.jar:META-INF/native/linux32/libjansi.so
```

Any ideas?

**Comment by agrawalpoonam** [comment]
I am getting the same error while executing the command sbt/sbt assembly 

[error] (spark-cassandra-connector-java/*:assembly) deduplicate: different file contents found in the following:
[error] /home/konfilarity/.ivy2/cache/io.netty/netty/bundles/netty-3.8.0.Final.jar:org/jboss/netty/bootstrap/Bootstrap.class
[error] /home/konfilarity/.ivy2/cache/org.jboss.netty/netty/bundles/netty-3.2.2.Final.jar:org/jboss/netty/bootstrap/Bootstrap.class

**Comment by feixiaohuijava** [comment]
could i comment?

**Comment by hendisantika** [comment]
I have same issue to with @agrawalpoonam ....
```
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /home/webdev/.ivy2/cache/io.netty/netty-transport-native-epoll/jars/netty-transport-native-epoll-4.0.42.Final-linux-x86_64.jar:META-INF/native/libnetty-transport-native-epoll.so
[error] /home/webdev/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.1.0.Final.jar:META-INF/native/libnetty-transport-native-epoll.so
[error] Total time: 60 s, completed Jan 17, 2017 1:48:31 PM
ERROR: Build failed: Process exited with: 1. Reason was:  ()
```

Could any one give an advice to me?
Thanks

**Comment by knightsss** [comment]
edit build.sbt
add this：
assemblyMergeStrategy in assembly := {
 case PathList("META-INF", xs @ _*) => MergeStrategy.discard
 case x => MergeStrategy.first
}

and 
edit ./project/plugins.sbt
add this:
addSbtPlugin("com.typesafe.sbt" % "sbt-site" % "0.7.0")

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.12.0")
